/* vocab-data.js — curated review vocabulary for the French course (A1–A2).

   Consumed by learn.js, glossary.js and the companion pages. Keyed by lesson
   number, plus a "titles" map, a "slugs" map (lesson -> page filename) and a
   "levels" map (lesson -> CEFR band). Each word is { fr, pron, en }.
   Safe to hand-edit — this file is the single source of truth for the review
   deck, the glossary and the auto-generated self-check quizzes. */
window.FRENCH_VOCAB = {
  "titles": {
    "1": "The French Alphabet & Pronunciation",
    "2": "Greetings & Essential Phrases",
    "3": "France vs Canadian French",
    "4": "Nouns, Gender & Articles",
    "5": "Être, Avoir & the Essential Verbs",
    "6": "Numbers, Time & Dates",
    "7": "The Present Tense",
    "8": "Family & Personal Descriptions",
    "9": "Adjectives, Adverbs & Comparisons",
    "10": "Negation & Asking Questions",
    "11": "Food & Dining",
    "12": "Possessives, Demonstratives & Quantities",
    "13": "Shopping & Money",
    "14": "Home, Household & Daily Routines",
    "15": "Reflexive Verbs, Commands & Polite Requests",
    "16": "Directions & Transportation",
    "17": "Talking About the Future",
    "18": "Hobbies & Daily Life",
    "19": "The Passé Composé",
    "20": "Health & the Body",
    "21": "The Imparfait & Past-Tense Choice",
    "22": "Weather & Seasons",
    "23": "Object Pronouns & Linking Ideas",
    "24": "Work & Education",
    "25": "Technology & Communication",
    "26": "Emotions & Relationships",
    "27": "Travel & Culture: France",
    "28": "Travel & Culture: Québec & Francophone Canada"
  },
  "slugs": {
    "1": "french_alphabet_pronunciation",
    "2": "french_greetings_essentials",
    "3": "french_france_vs_canada",
    "4": "french_grammar_nouns_articles",
    "5": "french_grammar_etre_avoir",
    "6": "french_numbers_time_dates",
    "7": "french_grammar_present_tense",
    "8": "french_family_descriptions",
    "9": "french_grammar_adjectives_adverbs",
    "10": "french_grammar_negation_questions",
    "11": "french_food_dining",
    "12": "french_grammar_possessives_quantities",
    "13": "french_shopping_money",
    "14": "french_home_household_routines",
    "15": "french_grammar_reflexives_commands",
    "16": "french_directions_transportation",
    "17": "french_grammar_future",
    "18": "french_hobbies_daily_life",
    "19": "french_grammar_passe_compose",
    "20": "french_health_body",
    "21": "french_grammar_imparfait",
    "22": "french_weather_seasons",
    "23": "french_grammar_pronouns_linking",
    "24": "french_work_education",
    "25": "french_technology_communication",
    "26": "french_emotions_relationships",
    "27": "french_travel_culture_france",
    "28": "french_travel_culture_canada"
  },
  "levels": {
    "1": "A1", "2": "A1", "3": "A1", "4": "A1", "5": "A1", "6": "A1", "7": "A1",
    "8": "A1", "9": "A1", "10": "A1", "11": "A1", "12": "A1", "13": "A1",
    "14": "A1", "15": "A1–A2", "16": "A2", "17": "A2", "18": "A2", "19": "A2",
    "20": "A2", "21": "A2", "22": "A2", "23": "A2", "24": "A2", "25": "A2",
    "26": "A2", "27": "A2", "28": "A2"
  },

  "1": [
    { "fr": "l'alphabet", "pron": "lal-fah-BAY", "en": "the alphabet" },
    { "fr": "un accent aigu", "pron": "uhn ak-sahn ay-GÜ", "en": "an acute accent (é)" },
    { "fr": "un accent grave", "pron": "uhn ak-sahn GRAHV", "en": "a grave accent (è)" },
    { "fr": "un accent circonflexe", "pron": "uhn ak-sahn seer-kohn-FLEX", "en": "a circumflex (ê)" },
    { "fr": "un tréma", "pron": "uhn tray-MAH", "en": "a diaeresis (ë)" },
    { "fr": "une cédille", "pron": "ün say-DEEY", "en": "a cedilla (ç)" },
    { "fr": "une voyelle", "pron": "ün vwah-YEL", "en": "a vowel" },
    { "fr": "une consonne", "pron": "ün kohn-SON", "en": "a consonant" },
    { "fr": "une syllabe", "pron": "ün see-LAB", "en": "a syllable" },
    { "fr": "la liaison", "pron": "lah lee-ay-ZOHN", "en": "liaison (linking sounds)" },
    { "fr": "une lettre muette", "pron": "ün letr mü-ET", "en": "a silent letter" },
    { "fr": "nasal", "pron": "nah-ZAL", "en": "nasal (of a vowel)" },
    { "fr": "prononcer", "pron": "pro-nohn-SAY", "en": "to pronounce" },
    { "fr": "répéter", "pron": "ray-pay-TAY", "en": "to repeat" },
    { "fr": "épeler", "pron": "ay-play", "en": "to spell out" },
    { "fr": "Comment ça s'écrit ?", "pron": "ko-mahn sah say-KREE", "en": "How is that spelled?" },
    { "fr": "Répétez, s'il vous plaît.", "pron": "ray-pay-TAY seel voo PLAY", "en": "Please repeat." },
    { "fr": "Plus lentement, s'il vous plaît.", "pron": "plü lahnt-MAHN", "en": "More slowly, please." }
  ],

  "2": [
    { "fr": "bonjour", "pron": "bohn-ZHOOR", "en": "hello, good day" },
    { "fr": "bonsoir", "pron": "bohn-SWAHR", "en": "good evening" },
    { "fr": "salut", "pron": "sah-LÜ", "en": "hi / bye (casual)" },
    { "fr": "au revoir", "pron": "oh ruh-VWAHR", "en": "goodbye" },
    { "fr": "bonne journée", "pron": "bun zhoor-NAY", "en": "have a good day" },
    { "fr": "à bientôt", "pron": "ah bee-en-TOH", "en": "see you soon" },
    { "fr": "à demain", "pron": "ah duh-MAN", "en": "see you tomorrow" },
    { "fr": "Comment ça va ?", "pron": "ko-mahn sah VAH", "en": "How are you?" },
    { "fr": "Ça va bien, merci.", "pron": "sah vah bee-EN mair-SEE", "en": "I'm well, thank you." },
    { "fr": "Je m'appelle...", "pron": "zhuh mah-PEL", "en": "My name is..." },
    { "fr": "Enchanté(e)", "pron": "ahn-shahn-TAY", "en": "Nice to meet you" },
    { "fr": "J'habite à...", "pron": "zhah-BEET ah", "en": "I live in..." },
    { "fr": "s'il vous plaît", "pron": "seel voo PLAY", "en": "please (formal)" },
    { "fr": "merci beaucoup", "pron": "mair-see boh-KOO", "en": "thank you very much" },
    { "fr": "de rien", "pron": "duh ree-EN", "en": "you're welcome" },
    { "fr": "excusez-moi", "pron": "ex-kü-zay MWAH", "en": "excuse me (formal)" },
    { "fr": "pardon", "pron": "par-DOHN", "en": "sorry, pardon me" },
    { "fr": "Je ne comprends pas.", "pron": "zhuh nuh kohn-prahn PAH", "en": "I don't understand." },
    { "fr": "Parlez-vous anglais ?", "pron": "par-lay voo ahn-GLAY", "en": "Do you speak English?" },
    { "fr": "d'accord", "pron": "dah-KOR", "en": "okay, agreed" }
  ],

  "3": [
    { "fr": "le français québécois", "pron": "luh frahn-say kay-bay-KWAH", "en": "Québécois French" },
    { "fr": "un accent", "pron": "uhn ak-SAHN", "en": "an accent" },
    { "fr": "le joual", "pron": "luh ZHWAL", "en": "working-class Québécois speech" },
    { "fr": "un anglicisme", "pron": "uhn ahn-glee-SEEZM", "en": "an English loanword" },
    { "fr": "un courriel", "pron": "uhn koo-ree-EL", "en": "an email (🇨🇦 preferred)" },
    { "fr": "la fin de semaine", "pron": "lah fan duh suh-MEN", "en": "the weekend (🇨🇦)" },
    { "fr": "le week-end", "pron": "luh week-END", "en": "the weekend (🇫🇷)" },
    { "fr": "le déjeuner", "pron": "luh day-zhuh-NAY", "en": "lunch (🇫🇷) / breakfast (🇨🇦)" },
    { "fr": "le dîner", "pron": "luh dee-NAY", "en": "dinner (🇫🇷) / lunch (🇨🇦)" },
    { "fr": "le souper", "pron": "luh soo-PAY", "en": "supper, dinner (🇨🇦)" },
    { "fr": "un char", "pron": "uhn SHAR", "en": "a car (🇨🇦 colloquial)" },
    { "fr": "une voiture", "pron": "ün vwah-TÜR", "en": "a car (standard)" },
    { "fr": "magasiner", "pron": "mah-gah-zee-NAY", "en": "to shop (🇨🇦)" },
    { "fr": "faire les magasins", "pron": "fair lay mah-gah-ZAN", "en": "to go shopping (🇫🇷)" },
    { "fr": "un chum", "pron": "uhn TCHOM", "en": "boyfriend, buddy (🇨🇦)" },
    { "fr": "une blonde", "pron": "ün BLOHND", "en": "girlfriend (🇨🇦)" },
    { "fr": "C'est le fun !", "pron": "say luh FUN", "en": "That's fun! (🇨🇦)" },
    { "fr": "pantoute", "pron": "pahn-TOOT", "en": "not at all (🇨🇦)" }
  ],

  "4": [
    { "fr": "le / la / les", "pron": "luh / lah / lay", "en": "the (definite articles)" },
    { "fr": "un / une / des", "pron": "uhn / ün / day", "en": "a, an, some (indefinite)" },
    { "fr": "du / de la", "pron": "dü / duh lah", "en": "some (partitive)" },
    { "fr": "masculin", "pron": "mas-kü-LAN", "en": "masculine" },
    { "fr": "féminin", "pron": "fay-mee-NAN", "en": "feminine" },
    { "fr": "le livre", "pron": "luh LEEVR", "en": "the book" },
    { "fr": "la table", "pron": "lah TABL", "en": "the table" },
    { "fr": "la maison", "pron": "lah may-ZOHN", "en": "the house" },
    { "fr": "le fromage", "pron": "luh fro-MAHZH", "en": "the cheese" },
    { "fr": "l'eau", "pron": "loh", "en": "the water (feminine)" },
    { "fr": "le pain", "pron": "luh PAN", "en": "the bread" },
    { "fr": "la voiture", "pron": "lah vwah-TÜR", "en": "the car" },
    { "fr": "J'aime le café.", "pron": "zhem luh kah-FAY", "en": "I like coffee (in general)." },
    { "fr": "Je bois du café.", "pron": "zhuh bwah dü kah-FAY", "en": "I drink (some) coffee." },
    { "fr": "Je n'ai pas de voiture.", "pron": "zhuh nay pah duh vwah-TÜR", "en": "I don't have a car." },
    { "fr": "beaucoup de", "pron": "boh-KOO duh", "en": "a lot of" },
    { "fr": "un peu de", "pron": "uhn puh duh", "en": "a little" },
    { "fr": "les chevaux", "pron": "lay shuh-VOH", "en": "the horses (irregular plural)" }
  ],

  "5": [
    { "fr": "je suis", "pron": "zhuh SWEE", "en": "I am" },
    { "fr": "tu es", "pron": "tü AY", "en": "you are (informal)" },
    { "fr": "nous sommes", "pron": "noo SOM", "en": "we are" },
    { "fr": "vous êtes", "pron": "voo-ZET", "en": "you are (formal/plural)" },
    { "fr": "ils sont", "pron": "eel SOHN", "en": "they are" },
    { "fr": "j'ai", "pron": "zhay", "en": "I have" },
    { "fr": "nous avons", "pron": "noo-zah-VOHN", "en": "we have" },
    { "fr": "ils ont", "pron": "eel-ZOHN", "en": "they have" },
    { "fr": "J'ai faim.", "pron": "zhay FAN", "en": "I'm hungry." },
    { "fr": "J'ai soif.", "pron": "zhay SWAHF", "en": "I'm thirsty." },
    { "fr": "J'ai vingt ans.", "pron": "zhay van-TAHN", "en": "I'm twenty years old." },
    { "fr": "J'ai besoin de...", "pron": "zhay buh-ZWAN duh", "en": "I need..." },
    { "fr": "J'ai envie de...", "pron": "zhay ahn-VEE duh", "en": "I feel like..." },
    { "fr": "je vais", "pron": "zhuh VAY", "en": "I go / I'm going" },
    { "fr": "nous allons", "pron": "noo-zah-LOHN", "en": "we go" },
    { "fr": "je fais", "pron": "zhuh FAY", "en": "I do / I make" },
    { "fr": "nous faisons", "pron": "noo fuh-ZOHN", "en": "we do" },
    { "fr": "il y a", "pron": "eel ee AH", "en": "there is / there are" },
    { "fr": "c'est", "pron": "say", "en": "it is, this is" },
    { "fr": "on", "pron": "ohn", "en": "we / one / people" }
  ],

  "6": [
    { "fr": "un, deux, trois", "pron": "uhn, duh, trwah", "en": "one, two, three" },
    { "fr": "dix", "pron": "dees", "en": "ten" },
    { "fr": "vingt", "pron": "van", "en": "twenty" },
    { "fr": "soixante-dix", "pron": "swah-sahnt-DEES", "en": "seventy (🇫🇷)" },
    { "fr": "quatre-vingts", "pron": "katr-VAN", "en": "eighty" },
    { "fr": "quatre-vingt-dix", "pron": "katr-van-DEES", "en": "ninety" },
    { "fr": "cent", "pron": "sahn", "en": "one hundred" },
    { "fr": "mille", "pron": "meel", "en": "one thousand" },
    { "fr": "Quelle heure est-il ?", "pron": "kel UHR ay-TEEL", "en": "What time is it?" },
    { "fr": "Il est trois heures.", "pron": "eel ay trwah-ZUHR", "en": "It's three o'clock." },
    { "fr": "et quart", "pron": "ay KAR", "en": "quarter past" },
    { "fr": "et demie", "pron": "ay duh-MEE", "en": "half past" },
    { "fr": "moins le quart", "pron": "mwan luh KAR", "en": "quarter to" },
    { "fr": "lundi", "pron": "luhn-DEE", "en": "Monday" },
    { "fr": "samedi", "pron": "sam-DEE", "en": "Saturday" },
    { "fr": "janvier", "pron": "zhahn-vee-AY", "en": "January" },
    { "fr": "juillet", "pron": "zhwee-YAY", "en": "July" },
    { "fr": "aujourd'hui", "pron": "oh-zhoor-DWEE", "en": "today" },
    { "fr": "demain", "pron": "duh-MAN", "en": "tomorrow" },
    { "fr": "hier", "pron": "ee-AIR", "en": "yesterday" }
  ],

  "7": [
    { "fr": "parler", "pron": "par-LAY", "en": "to speak" },
    { "fr": "habiter", "pron": "ah-bee-TAY", "en": "to live (somewhere)" },
    { "fr": "travailler", "pron": "trah-vah-YAY", "en": "to work" },
    { "fr": "aimer", "pron": "eh-MAY", "en": "to like, to love" },
    { "fr": "regarder", "pron": "ruh-gar-DAY", "en": "to watch" },
    { "fr": "écouter", "pron": "ay-koo-TAY", "en": "to listen to" },
    { "fr": "manger", "pron": "mahn-ZHAY", "en": "to eat" },
    { "fr": "acheter", "pron": "ahsh-TAY", "en": "to buy" },
    { "fr": "finir", "pron": "fee-NEER", "en": "to finish" },
    { "fr": "choisir", "pron": "shwah-ZEER", "en": "to choose" },
    { "fr": "attendre", "pron": "ah-TAHNDR", "en": "to wait for" },
    { "fr": "vendre", "pron": "VAHNDR", "en": "to sell" },
    { "fr": "je veux", "pron": "zhuh VUH", "en": "I want" },
    { "fr": "je peux", "pron": "zhuh PUH", "en": "I can" },
    { "fr": "je dois", "pron": "zhuh DWAH", "en": "I must, I have to" },
    { "fr": "je sais", "pron": "zhuh SAY", "en": "I know (a fact)" },
    { "fr": "je connais", "pron": "zhuh ko-NAY", "en": "I know (a person, a place)" },
    { "fr": "je prends", "pron": "zhuh PRAHN", "en": "I take" },
    { "fr": "je bois", "pron": "zhuh BWAH", "en": "I drink" },
    { "fr": "Tu peux répéter ?", "pron": "tü puh ray-pay-TAY", "en": "Can you repeat that?" }
  ],

  "8": [
    { "fr": "la famille", "pron": "lah fah-MEEY", "en": "the family" },
    { "fr": "le père", "pron": "luh PAIR", "en": "the father" },
    { "fr": "la mère", "pron": "lah MAIR", "en": "the mother" },
    { "fr": "le frère", "pron": "luh FRAIR", "en": "the brother" },
    { "fr": "la soeur", "pron": "lah SUHR", "en": "the sister" },
    { "fr": "les parents", "pron": "lay pah-RAHN", "en": "the parents" },
    { "fr": "les enfants", "pron": "lay-zahn-FAHN", "en": "the children" },
    { "fr": "le fils", "pron": "luh FEES", "en": "the son" },
    { "fr": "la fille", "pron": "lah FEEY", "en": "the daughter, the girl" },
    { "fr": "les grands-parents", "pron": "lay grahn-pah-RAHN", "en": "the grandparents" },
    { "fr": "le mari", "pron": "luh mah-REE", "en": "the husband" },
    { "fr": "la femme", "pron": "lah FAM", "en": "the wife, the woman" },
    { "fr": "grand(e)", "pron": "grahn / grahnd", "en": "tall, big" },
    { "fr": "petit(e)", "pron": "puh-TEE / puh-TEET", "en": "short, small" },
    { "fr": "les cheveux", "pron": "lay shuh-VUH", "en": "the hair" },
    { "fr": "les yeux", "pron": "lay-ZYUH", "en": "the eyes" },
    { "fr": "sympa", "pron": "san-PAH", "en": "nice, friendly" },
    { "fr": "drôle", "pron": "drohl", "en": "funny" },
    { "fr": "Il ressemble à son père.", "pron": "eel ruh-SAHNBL", "en": "He looks like his father." }
  ],

  "9": [
    { "fr": "vert / verte", "pron": "vair / vairt", "en": "green" },
    { "fr": "blanc / blanche", "pron": "blahn / blahnsh", "en": "white" },
    { "fr": "beau / belle", "pron": "boh / bel", "en": "beautiful" },
    { "fr": "nouveau / nouvelle", "pron": "noo-VOH / noo-VEL", "en": "new" },
    { "fr": "vieux / vieille", "pron": "vee-UH / vee-AY", "en": "old" },
    { "fr": "heureux / heureuse", "pron": "uh-RUH / uh-RUHZ", "en": "happy" },
    { "fr": "gentil / gentille", "pron": "zhahn-TEE / zhahn-TEEY", "en": "kind" },
    { "fr": "cher / chère", "pron": "shair", "en": "expensive, dear" },
    { "fr": "lentement", "pron": "lahnt-MAHN", "en": "slowly" },
    { "fr": "vraiment", "pron": "vray-MAHN", "en": "really" },
    { "fr": "bien", "pron": "bee-EN", "en": "well (adverb)" },
    { "fr": "bon / bonne", "pron": "bohn / bun", "en": "good (adjective)" },
    { "fr": "souvent", "pron": "soo-VAHN", "en": "often" },
    { "fr": "toujours", "pron": "too-ZHOOR", "en": "always, still" },
    { "fr": "plus... que", "pron": "plü... kuh", "en": "more... than" },
    { "fr": "moins... que", "pron": "mwan... kuh", "en": "less... than" },
    { "fr": "aussi... que", "pron": "oh-SEE... kuh", "en": "as... as" },
    { "fr": "meilleur", "pron": "may-YUHR", "en": "better (adjective)" },
    { "fr": "mieux", "pron": "mee-UH", "en": "better (adverb)" },
    { "fr": "le plus grand", "pron": "luh plü GRAHN", "en": "the biggest" }
  ],

  "10": [
    { "fr": "ne... pas", "pron": "nuh... pah", "en": "not" },
    { "fr": "ne... jamais", "pron": "nuh... zhah-MAY", "en": "never" },
    { "fr": "ne... plus", "pron": "nuh... PLÜ", "en": "no longer, no more" },
    { "fr": "ne... rien", "pron": "nuh... ree-EN", "en": "nothing" },
    { "fr": "ne... personne", "pron": "nuh... pair-SON", "en": "nobody" },
    { "fr": "pas encore", "pron": "pah-zahn-KOR", "en": "not yet" },
    { "fr": "ne... que", "pron": "nuh... kuh", "en": "only" },
    { "fr": "Je ne sais pas.", "pron": "zhuh nuh say PAH", "en": "I don't know." },
    { "fr": "Est-ce que... ?", "pron": "ess kuh", "en": "(question opener)" },
    { "fr": "qui", "pron": "kee", "en": "who" },
    { "fr": "où", "pron": "oo", "en": "where" },
    { "fr": "quand", "pron": "kahn", "en": "when" },
    { "fr": "pourquoi", "pron": "poor-KWAH", "en": "why" },
    { "fr": "comment", "pron": "ko-MAHN", "en": "how" },
    { "fr": "combien", "pron": "kohn-bee-EN", "en": "how much, how many" },
    { "fr": "quel / quelle", "pron": "kel", "en": "which, what" },
    { "fr": "Qu'est-ce que c'est ?", "pron": "kess kuh SAY", "en": "What is it?" },
    { "fr": "si", "pron": "see", "en": "yes (contradicting a negative)" },
    { "fr": "Quel âge as-tu ?", "pron": "kel ahzh ah-TÜ", "en": "How old are you?" }
  ],

  "11": [
    { "fr": "le petit-déjeuner", "pron": "luh puh-tee day-zhuh-NAY", "en": "breakfast (🇫🇷)" },
    { "fr": "le repas", "pron": "luh ruh-PAH", "en": "the meal" },
    { "fr": "l'entrée", "pron": "lahn-TRAY", "en": "the starter, appetiser" },
    { "fr": "le plat principal", "pron": "luh plah pran-see-PAL", "en": "the main course" },
    { "fr": "le dessert", "pron": "luh day-SAIR", "en": "dessert" },
    { "fr": "la carte", "pron": "lah KART", "en": "the menu" },
    { "fr": "le menu du jour", "pron": "luh muh-nü dü ZHOOR", "en": "the set menu of the day" },
    { "fr": "l'addition", "pron": "lah-dee-SYOHN", "en": "the bill, the check" },
    { "fr": "le pourboire", "pron": "luh poor-BWAHR", "en": "the tip" },
    { "fr": "un serveur / une serveuse", "pron": "uhn sair-VUHR", "en": "a waiter / waitress" },
    { "fr": "Je voudrais...", "pron": "zhuh voo-DRAY", "en": "I would like..." },
    { "fr": "L'addition, s'il vous plaît.", "pron": "lah-dee-syohn seel voo PLAY", "en": "The bill, please." },
    { "fr": "une baguette", "pron": "ün bah-GET", "en": "a baguette" },
    { "fr": "le vin", "pron": "luh VAN", "en": "wine" },
    { "fr": "l'eau du robinet", "pron": "loh dü ro-bee-NAY", "en": "tap water" },
    { "fr": "délicieux", "pron": "day-lee-see-UH", "en": "delicious" },
    { "fr": "avoir faim", "pron": "ah-vwahr FAN", "en": "to be hungry" },
    { "fr": "la poutine", "pron": "lah poo-TEEN", "en": "poutine (🇨🇦)" },
    { "fr": "une cabane à sucre", "pron": "ün kah-ban ah SÜKR", "en": "a sugar shack (🇨🇦)" },
    { "fr": "Bon appétit !", "pron": "bohn-ah-pay-TEE", "en": "Enjoy your meal!" }
  ],

  "12": [
    { "fr": "mon / ma / mes", "pron": "mohn / mah / may", "en": "my" },
    { "fr": "ton / ta / tes", "pron": "tohn / tah / tay", "en": "your (informal)" },
    { "fr": "son / sa / ses", "pron": "sohn / sah / say", "en": "his, her, its" },
    { "fr": "notre / nos", "pron": "notr / noh", "en": "our" },
    { "fr": "votre / vos", "pron": "votr / voh", "en": "your (formal, plural)" },
    { "fr": "leur / leurs", "pron": "luhr", "en": "their" },
    { "fr": "ce / cet / cette / ces", "pron": "suh / set / set / say", "en": "this, that, these, those" },
    { "fr": "C'est à moi.", "pron": "say tah MWAH", "en": "It's mine." },
    { "fr": "C'est à qui ?", "pron": "say tah KEE", "en": "Whose is this?" },
    { "fr": "assez de", "pron": "ah-SAY duh", "en": "enough" },
    { "fr": "trop de", "pron": "troh duh", "en": "too much, too many" },
    { "fr": "une bouteille de", "pron": "ün boo-TAY duh", "en": "a bottle of" },
    { "fr": "un verre de", "pron": "uhn VAIR duh", "en": "a glass of" },
    { "fr": "une tranche de", "pron": "ün TRAHNSH duh", "en": "a slice of" },
    { "fr": "un kilo de", "pron": "uhn kee-LOH duh", "en": "a kilo of" },
    { "fr": "quelques", "pron": "KEL-kuh", "en": "a few" },
    { "fr": "plusieurs", "pron": "plü-zee-UHR", "en": "several" },
    { "fr": "chaque", "pron": "shahk", "en": "each, every" },
    { "fr": "tous les jours", "pron": "too lay ZHOOR", "en": "every day" }
  ],

  "13": [
    { "fr": "un magasin", "pron": "uhn mah-gah-ZAN", "en": "a shop, a store" },
    { "fr": "une boulangerie", "pron": "ün boo-lahn-zhuh-REE", "en": "a bakery" },
    { "fr": "un marché", "pron": "uhn mar-SHAY", "en": "a market" },
    { "fr": "une caisse", "pron": "ün KESS", "en": "a checkout, a till" },
    { "fr": "le prix", "pron": "luh PREE", "en": "the price" },
    { "fr": "cher / pas cher", "pron": "shair / pah shair", "en": "expensive / cheap" },
    { "fr": "un euro", "pron": "uhn uh-ROH", "en": "a euro" },
    { "fr": "un dollar", "pron": "uhn do-LAR", "en": "a dollar" },
    { "fr": "la monnaie", "pron": "lah mo-NAY", "en": "change (coins)" },
    { "fr": "payer par carte", "pron": "pay-YAY par KART", "en": "to pay by card" },
    { "fr": "en espèces", "pron": "ahn-ness-PESS", "en": "in cash" },
    { "fr": "les soldes", "pron": "lay SOLD", "en": "the sales" },
    { "fr": "une taille", "pron": "ün TYE", "en": "a size (clothing)" },
    { "fr": "une pointure", "pron": "ün pwan-TÜR", "en": "a shoe size" },
    { "fr": "essayer", "pron": "ay-say-YAY", "en": "to try on" },
    { "fr": "Ça coûte combien ?", "pron": "sah koot kohn-bee-EN", "en": "How much does it cost?" },
    { "fr": "Je regarde, merci.", "pron": "zhuh ruh-GARD", "en": "I'm just looking, thanks." },
    { "fr": "un dépanneur", "pron": "uhn day-pah-NUHR", "en": "a corner store (🇨🇦)" },
    { "fr": "les taxes", "pron": "lay TAX", "en": "sales taxes (🇨🇦, added at the till)" }
  ],

  "14": [
    { "fr": "une maison", "pron": "ün may-ZOHN", "en": "a house" },
    { "fr": "un appartement", "pron": "uhn ah-par-tuh-MAHN", "en": "an apartment" },
    { "fr": "le rez-de-chaussée", "pron": "luh ray-duh-shoh-SAY", "en": "the ground floor" },
    { "fr": "la cuisine", "pron": "lah kwee-ZEEN", "en": "the kitchen" },
    { "fr": "le salon", "pron": "luh sah-LOHN", "en": "the living room" },
    { "fr": "la chambre", "pron": "lah SHAHNBR", "en": "the bedroom" },
    { "fr": "la salle de bains", "pron": "lah sahl duh BAN", "en": "the bathroom" },
    { "fr": "les toilettes", "pron": "lay twah-LET", "en": "the toilet" },
    { "fr": "un lit", "pron": "uhn LEE", "en": "a bed" },
    { "fr": "une chaise", "pron": "ün SHEZ", "en": "a chair" },
    { "fr": "un canapé", "pron": "uhn kah-nah-PAY", "en": "a sofa" },
    { "fr": "un placard", "pron": "uhn plah-KAR", "en": "a cupboard, a closet" },
    { "fr": "faire le ménage", "pron": "fair luh may-NAHZH", "en": "to do the housework" },
    { "fr": "faire la vaisselle", "pron": "fair lah vay-SEL", "en": "to do the dishes" },
    { "fr": "faire la lessive", "pron": "fair lah lay-SEEV", "en": "to do the laundry" },
    { "fr": "faire les courses", "pron": "fair lay KOORS", "en": "to do the grocery shopping" },
    { "fr": "passer l'aspirateur", "pron": "pah-say lahs-pee-rah-TUHR", "en": "to vacuum" },
    { "fr": "ranger", "pron": "rahn-ZHAY", "en": "to tidy up" },
    { "fr": "le loyer", "pron": "luh lwah-YAY", "en": "the rent" },
    { "fr": "un voisin", "pron": "uhn vwah-ZAN", "en": "a neighbour" }
  ],

  "15": [
    { "fr": "se réveiller", "pron": "suh ray-vay-YAY", "en": "to wake up" },
    { "fr": "se lever", "pron": "suh luh-VAY", "en": "to get up" },
    { "fr": "se doucher", "pron": "suh doo-SHAY", "en": "to shower" },
    { "fr": "s'habiller", "pron": "sah-bee-YAY", "en": "to get dressed" },
    { "fr": "se brosser les dents", "pron": "suh bro-say lay DAHN", "en": "to brush one's teeth" },
    { "fr": "se dépêcher", "pron": "suh day-pay-SHAY", "en": "to hurry" },
    { "fr": "se reposer", "pron": "suh ruh-poh-ZAY", "en": "to rest" },
    { "fr": "se coucher", "pron": "suh koo-SHAY", "en": "to go to bed" },
    { "fr": "s'amuser", "pron": "sah-mü-ZAY", "en": "to have fun" },
    { "fr": "s'appeler", "pron": "sah-play", "en": "to be called (named)" },
    { "fr": "Écoutez !", "pron": "ay-koo-TAY", "en": "Listen! (formal)" },
    { "fr": "Attends !", "pron": "ah-TAHN", "en": "Wait! (informal)" },
    { "fr": "Allons-y !", "pron": "ah-lohn-ZEE", "en": "Let's go!" },
    { "fr": "Asseyez-vous.", "pron": "ah-say-yay VOO", "en": "Sit down. (formal)" },
    { "fr": "Soyez patient.", "pron": "swah-yay pah-SYAHN", "en": "Be patient." },
    { "fr": "Je voudrais...", "pron": "zhuh voo-DRAY", "en": "I would like..." },
    { "fr": "J'aimerais...", "pron": "zhem-RAY", "en": "I would like... (softer)" },
    { "fr": "Pourriez-vous... ?", "pron": "poo-ree-ay VOO", "en": "Could you...?" },
    { "fr": "Veuillez patienter.", "pron": "vuh-yay pah-syahn-TAY", "en": "Please hold / wait. (formal)" }
  ],

  "16": [
    { "fr": "à droite", "pron": "ah DRWAHT", "en": "on / to the right" },
    { "fr": "à gauche", "pron": "ah GOHSH", "en": "on / to the left" },
    { "fr": "tout droit", "pron": "too DRWAH", "en": "straight ahead" },
    { "fr": "en face de", "pron": "ahn FAHS duh", "en": "across from" },
    { "fr": "à côté de", "pron": "ah koh-TAY duh", "en": "next to" },
    { "fr": "loin / près", "pron": "lwan / pray", "en": "far / near" },
    { "fr": "tourner", "pron": "toor-NAY", "en": "to turn" },
    { "fr": "traverser", "pron": "trah-vair-SAY", "en": "to cross" },
    { "fr": "un carrefour", "pron": "uhn kar-FOOR", "en": "an intersection" },
    { "fr": "un feu rouge", "pron": "uhn fuh ROOZH", "en": "a traffic light" },
    { "fr": "le métro", "pron": "luh may-TROH", "en": "the subway" },
    { "fr": "un arrêt de bus", "pron": "uhn ah-ray duh BÜS", "en": "a bus stop" },
    { "fr": "une gare", "pron": "ün GAR", "en": "a train station" },
    { "fr": "un billet", "pron": "uhn bee-YAY", "en": "a ticket" },
    { "fr": "un aller-retour", "pron": "uhn ah-lay ruh-TOOR", "en": "a return ticket" },
    { "fr": "composter", "pron": "kohn-pos-TAY", "en": "to validate (a ticket, 🇫🇷)" },
    { "fr": "Où est... ?", "pron": "oo AY", "en": "Where is...?" },
    { "fr": "Je suis perdu(e).", "pron": "zhuh swee pair-DÜ", "en": "I'm lost." },
    { "fr": "à pied", "pron": "ah pee-AY", "en": "on foot" }
  ],

  "17": [
    { "fr": "je vais partir", "pron": "zhuh vay par-TEER", "en": "I'm going to leave" },
    { "fr": "on va voir", "pron": "ohn vah VWAHR", "en": "we'll see" },
    { "fr": "je serai", "pron": "zhuh suh-RAY", "en": "I will be" },
    { "fr": "j'aurai", "pron": "zhoh-RAY", "en": "I will have" },
    { "fr": "j'irai", "pron": "zhee-RAY", "en": "I will go" },
    { "fr": "je ferai", "pron": "zhuh fuh-RAY", "en": "I will do" },
    { "fr": "je viendrai", "pron": "zhuh vee-en-DRAY", "en": "I will come" },
    { "fr": "je pourrai", "pron": "zhuh poo-RAY", "en": "I will be able to" },
    { "fr": "il faudra", "pron": "eel foh-DRAH", "en": "it will be necessary" },
    { "fr": "je viens de...", "pron": "zhuh vee-en duh", "en": "I have just..." },
    { "fr": "demain", "pron": "duh-MAN", "en": "tomorrow" },
    { "fr": "après-demain", "pron": "ah-pray duh-MAN", "en": "the day after tomorrow" },
    { "fr": "la semaine prochaine", "pron": "lah suh-men pro-SHEN", "en": "next week" },
    { "fr": "dans deux jours", "pron": "dahn duh ZHOOR", "en": "in two days" },
    { "fr": "bientôt", "pron": "bee-en-TOH", "en": "soon" },
    { "fr": "plus tard", "pron": "plü TAR", "en": "later" },
    { "fr": "un jour", "pron": "uhn ZHOOR", "en": "one day, someday" },
    { "fr": "dès que", "pron": "day kuh", "en": "as soon as" }
  ],

  "18": [
    { "fr": "un passe-temps", "pron": "uhn pahs-TAHN", "en": "a hobby" },
    { "fr": "le temps libre", "pron": "luh tahn LEEBR", "en": "free time" },
    { "fr": "jouer à", "pron": "zhoo-AY ah", "en": "to play (a sport or game)" },
    { "fr": "jouer de", "pron": "zhoo-AY duh", "en": "to play (an instrument)" },
    { "fr": "faire du sport", "pron": "fair dü SPOR", "en": "to do sport" },
    { "fr": "le football", "pron": "luh foot-BOL", "en": "soccer" },
    { "fr": "la natation", "pron": "lah nah-tah-SYOHN", "en": "swimming" },
    { "fr": "le vélo", "pron": "luh vay-LOH", "en": "cycling, a bike" },
    { "fr": "la randonnée", "pron": "lah rahn-do-NAY", "en": "hiking" },
    { "fr": "lire", "pron": "leer", "en": "to read" },
    { "fr": "écouter de la musique", "pron": "ay-koo-tay duh lah mü-ZEEK", "en": "to listen to music" },
    { "fr": "aller au cinéma", "pron": "ah-lay oh see-nay-MAH", "en": "to go to the cinema" },
    { "fr": "sortir avec des amis", "pron": "sor-TEER ah-vek day-zah-MEE", "en": "to go out with friends" },
    { "fr": "cuisiner", "pron": "kwee-zee-NAY", "en": "to cook" },
    { "fr": "se promener", "pron": "suh prom-NAY", "en": "to go for a walk" },
    { "fr": "d'habitude", "pron": "dah-bee-TÜD", "en": "usually" },
    { "fr": "le week-end", "pron": "luh week-END", "en": "the weekend" },
    { "fr": "Ça te dit ?", "pron": "sah tuh DEE", "en": "Do you fancy it?" }
  ],

  "19": [
    { "fr": "j'ai mangé", "pron": "zhay mahn-ZHAY", "en": "I ate, I have eaten" },
    { "fr": "j'ai fait", "pron": "zhay FAY", "en": "I did, I made" },
    { "fr": "j'ai pris", "pron": "zhay PREE", "en": "I took" },
    { "fr": "j'ai vu", "pron": "zhay VÜ", "en": "I saw" },
    { "fr": "j'ai eu", "pron": "zhay Ü", "en": "I had" },
    { "fr": "j'ai été", "pron": "zhay ay-TAY", "en": "I was, I have been" },
    { "fr": "j'ai dit", "pron": "zhay DEE", "en": "I said" },
    { "fr": "j'ai écrit", "pron": "zhay ay-KREE", "en": "I wrote" },
    { "fr": "j'ai ouvert", "pron": "zhay oo-VAIR", "en": "I opened" },
    { "fr": "je suis allé(e)", "pron": "zhuh swee-zah-LAY", "en": "I went" },
    { "fr": "je suis parti(e)", "pron": "zhuh swee par-TEE", "en": "I left" },
    { "fr": "je suis arrivé(e)", "pron": "zhuh swee-zah-ree-VAY", "en": "I arrived" },
    { "fr": "je suis rentré(e)", "pron": "zhuh swee rahn-TRAY", "en": "I went home" },
    { "fr": "je me suis levé(e)", "pron": "zhuh muh swee luh-VAY", "en": "I got up" },
    { "fr": "Je n'ai pas compris.", "pron": "zhuh nay pah kohn-PREE", "en": "I didn't understand." },
    { "fr": "hier", "pron": "ee-AIR", "en": "yesterday" },
    { "fr": "la semaine dernière", "pron": "lah suh-men dair-nee-AIR", "en": "last week" },
    { "fr": "il y a deux jours", "pron": "eel ee ah duh ZHOOR", "en": "two days ago" },
    { "fr": "déjà", "pron": "day-ZHAH", "en": "already" }
  ],

  "20": [
    { "fr": "le corps", "pron": "luh KOR", "en": "the body" },
    { "fr": "la tête", "pron": "lah TET", "en": "the head" },
    { "fr": "la gorge", "pron": "lah GORZH", "en": "the throat" },
    { "fr": "le ventre", "pron": "luh VAHNTR", "en": "the stomach, the belly" },
    { "fr": "le dos", "pron": "luh DOH", "en": "the back" },
    { "fr": "la jambe", "pron": "lah ZHAHNB", "en": "the leg" },
    { "fr": "le bras", "pron": "luh BRAH", "en": "the arm" },
    { "fr": "la main", "pron": "lah MAN", "en": "the hand" },
    { "fr": "J'ai mal à la tête.", "pron": "zhay mal ah lah TET", "en": "I have a headache." },
    { "fr": "Je suis malade.", "pron": "zhuh swee mah-LAHD", "en": "I'm ill." },
    { "fr": "avoir de la fièvre", "pron": "ah-vwahr duh lah fee-EVR", "en": "to have a fever" },
    { "fr": "tousser", "pron": "too-SAY", "en": "to cough" },
    { "fr": "un médecin", "pron": "uhn mayd-SAN", "en": "a doctor" },
    { "fr": "une pharmacie", "pron": "ün far-mah-SEE", "en": "a pharmacy" },
    { "fr": "une ordonnance", "pron": "ün or-do-NAHNS", "en": "a prescription" },
    { "fr": "un médicament", "pron": "uhn may-dee-kah-MAHN", "en": "a medicine" },
    { "fr": "les urgences", "pron": "lay-zür-ZHAHNS", "en": "the emergency room" },
    { "fr": "Appelez une ambulance !", "pron": "ah-play ün ahn-bü-LAHNS", "en": "Call an ambulance!" },
    { "fr": "depuis trois jours", "pron": "duh-pwee trwah ZHOOR", "en": "for three days" }
  ],

  "21": [
    { "fr": "j'étais", "pron": "zhay-TAY", "en": "I was" },
    { "fr": "il y avait", "pron": "eel ee ah-VAY", "en": "there was, there were" },
    { "fr": "je faisais", "pron": "zhuh fuh-ZAY", "en": "I was doing, I used to do" },
    { "fr": "j'avais", "pron": "zhah-VAY", "en": "I had, I used to have" },
    { "fr": "je voulais", "pron": "zhuh voo-LAY", "en": "I wanted" },
    { "fr": "je savais", "pron": "zhuh sah-VAY", "en": "I knew" },
    { "fr": "j'habitais", "pron": "zhah-bee-TAY", "en": "I used to live" },
    { "fr": "il pleuvait", "pron": "eel pluh-VAY", "en": "it was raining" },
    { "fr": "il faisait froid", "pron": "eel fuh-zay FRWAH", "en": "it was cold" },
    { "fr": "quand j'étais petit(e)", "pron": "kahn zhay-tay puh-TEE", "en": "when I was little" },
    { "fr": "à l'époque", "pron": "ah lay-POK", "en": "back then" },
    { "fr": "pendant que", "pron": "pahn-dahn kuh", "en": "while" },
    { "fr": "soudain", "pron": "soo-DAN", "en": "suddenly" },
    { "fr": "tout à coup", "pron": "too tah KOO", "en": "all of a sudden" },
    { "fr": "chaque été", "pron": "shahk ay-TAY", "en": "every summer" },
    { "fr": "Si on allait... ?", "pron": "see ohn nah-LAY", "en": "How about going...?" },
    { "fr": "j'ai su", "pron": "zhay SÜ", "en": "I found out" },
    { "fr": "j'ai connu", "pron": "zhay ko-NÜ", "en": "I met (for the first time)" }
  ],

  "22": [
    { "fr": "le temps", "pron": "luh TAHN", "en": "the weather" },
    { "fr": "Quel temps fait-il ?", "pron": "kel tahn fay-TEEL", "en": "What's the weather like?" },
    { "fr": "Il fait beau.", "pron": "eel fay BOH", "en": "The weather is nice." },
    { "fr": "Il fait chaud.", "pron": "eel fay SHOH", "en": "It's hot." },
    { "fr": "Il fait froid.", "pron": "eel fay FRWAH", "en": "It's cold." },
    { "fr": "Il pleut.", "pron": "eel PLUH", "en": "It's raining." },
    { "fr": "Il neige.", "pron": "eel NEZH", "en": "It's snowing." },
    { "fr": "Il y a du vent.", "pron": "eel ee ah dü VAHN", "en": "It's windy." },
    { "fr": "un nuage", "pron": "uhn nü-AHZH", "en": "a cloud" },
    { "fr": "le soleil", "pron": "luh so-LAY", "en": "the sun" },
    { "fr": "la pluie", "pron": "lah PLWEE", "en": "the rain" },
    { "fr": "la neige", "pron": "lah NEZH", "en": "the snow" },
    { "fr": "le printemps", "pron": "luh pran-TAHN", "en": "spring" },
    { "fr": "l'été", "pron": "lay-TAY", "en": "summer" },
    { "fr": "l'automne", "pron": "loh-TON", "en": "autumn, fall" },
    { "fr": "l'hiver", "pron": "lee-VAIR", "en": "winter" },
    { "fr": "le verglas", "pron": "luh vair-GLAH", "en": "black ice" },
    { "fr": "une tuque", "pron": "ün TÜK", "en": "a winter hat (🇨🇦)" },
    { "fr": "Il fait moins vingt.", "pron": "eel fay mwan VAN", "en": "It's minus twenty." }
  ],

  "23": [
    { "fr": "le / la / les", "pron": "luh / lah / lay", "en": "him, her, it, them (direct object)" },
    { "fr": "lui", "pron": "lwee", "en": "to him, to her" },
    { "fr": "leur", "pron": "luhr", "en": "to them" },
    { "fr": "y", "pron": "ee", "en": "there, about it" },
    { "fr": "en", "pron": "ahn", "en": "some, of it, of them" },
    { "fr": "Je le vois.", "pron": "zhuh luh VWAH", "en": "I see him / it." },
    { "fr": "Je lui parle.", "pron": "zhuh lwee PARL", "en": "I'm talking to him / her." },
    { "fr": "J'y vais.", "pron": "zhee VAY", "en": "I'm going there." },
    { "fr": "J'en veux.", "pron": "zhahn VUH", "en": "I want some." },
    { "fr": "moi / toi / lui / elle", "pron": "mwah / twah / lwee / el", "en": "me / you / him / her (stressed)" },
    { "fr": "chez eux", "pron": "shay ZUH", "en": "at their place" },
    { "fr": "qui", "pron": "kee", "en": "who, which (subject)" },
    { "fr": "que", "pron": "kuh", "en": "that, which (object)" },
    { "fr": "où", "pron": "oo", "en": "where, when (relative)" },
    { "fr": "parce que", "pron": "pars kuh", "en": "because" },
    { "fr": "donc", "pron": "dohnk", "en": "so, therefore" },
    { "fr": "ensuite", "pron": "ahn-SWEET", "en": "then, next" },
    { "fr": "par contre", "pron": "par KOHNTR", "en": "on the other hand" },
    { "fr": "enfin", "pron": "ahn-FAN", "en": "finally" }
  ],

  "24": [
    { "fr": "le travail", "pron": "luh trah-VYE", "en": "work, a job" },
    { "fr": "un emploi", "pron": "uhn ahn-PLWAH", "en": "a job, employment" },
    { "fr": "une entreprise", "pron": "ün ahn-truh-PREEZ", "en": "a company" },
    { "fr": "un bureau", "pron": "uhn bü-ROH", "en": "an office, a desk" },
    { "fr": "une réunion", "pron": "ün ray-ü-NYOHN", "en": "a meeting" },
    { "fr": "un collègue", "pron": "uhn ko-LEG", "en": "a colleague" },
    { "fr": "un patron", "pron": "uhn pah-TROHN", "en": "a boss" },
    { "fr": "le salaire", "pron": "luh sah-LAIR", "en": "the salary" },
    { "fr": "un horaire", "pron": "uhn o-RAIR", "en": "a schedule" },
    { "fr": "un professeur", "pron": "uhn pro-feh-SUHR", "en": "a teacher" },
    { "fr": "un ingénieur", "pron": "uhn an-zhay-nee-UHR", "en": "an engineer" },
    { "fr": "une infirmière", "pron": "ün an-feer-mee-AIR", "en": "a nurse" },
    { "fr": "l'école", "pron": "lay-KOL", "en": "school" },
    { "fr": "le lycée", "pron": "luh lee-SAY", "en": "high school (🇫🇷)" },
    { "fr": "l'université", "pron": "lü-nee-vair-see-TAY", "en": "university" },
    { "fr": "le cégep", "pron": "luh say-ZHEP", "en": "pre-university college (🇨🇦)" },
    { "fr": "étudier", "pron": "ay-tü-dee-AY", "en": "to study" },
    { "fr": "un diplôme", "pron": "uhn dee-PLOHM", "en": "a degree, a diploma" },
    { "fr": "Qu'est-ce que vous faites dans la vie ?", "pron": "kess kuh voo FET", "en": "What do you do for a living?" }
  ],

  "25": [
    { "fr": "un ordinateur", "pron": "uhn or-dee-nah-TUHR", "en": "a computer" },
    { "fr": "un portable", "pron": "uhn por-TABL", "en": "a mobile phone / a laptop" },
    { "fr": "un téléphone", "pron": "uhn tay-lay-FON", "en": "a telephone" },
    { "fr": "l'écran", "pron": "lay-KRAHN", "en": "the screen" },
    { "fr": "le clavier", "pron": "luh klah-vee-AY", "en": "the keyboard" },
    { "fr": "un courriel", "pron": "uhn koo-ree-EL", "en": "an email (🇨🇦)" },
    { "fr": "un mail", "pron": "uhn MEL", "en": "an email (🇫🇷)" },
    { "fr": "un mot de passe", "pron": "uhn moh duh PAHS", "en": "a password" },
    { "fr": "le wifi", "pron": "luh wee-FEE", "en": "the wifi" },
    { "fr": "télécharger", "pron": "tay-lay-shar-ZHAY", "en": "to download" },
    { "fr": "envoyer un message", "pron": "ahn-vwah-yay uhn may-SAHZH", "en": "to send a message" },
    { "fr": "un réseau social", "pron": "uhn ray-zoh so-SYAL", "en": "a social network" },
    { "fr": "une application", "pron": "ün ah-plee-kah-SYOHN", "en": "an app" },
    { "fr": "éteindre", "pron": "ay-TANDR", "en": "to turn off" },
    { "fr": "allumer", "pron": "ah-lü-MAY", "en": "to turn on" },
    { "fr": "Ça ne marche pas.", "pron": "sah nuh marsh PAH", "en": "It's not working." },
    { "fr": "Quel est le code wifi ?", "pron": "kel ay luh kod wee-FEE", "en": "What's the wifi password?" },
    { "fr": "un appel vidéo", "pron": "uhn ah-pel vee-day-OH", "en": "a video call" }
  ],

  "26": [
    { "fr": "content(e)", "pron": "kohn-TAHN / kohn-TAHNT", "en": "happy, pleased" },
    { "fr": "triste", "pron": "treest", "en": "sad" },
    { "fr": "fatigué(e)", "pron": "fah-tee-GAY", "en": "tired" },
    { "fr": "en colère", "pron": "ahn ko-LAIR", "en": "angry" },
    { "fr": "inquiet / inquiète", "pron": "an-kee-AY / an-kee-ET", "en": "worried" },
    { "fr": "avoir peur", "pron": "ah-vwahr PUHR", "en": "to be afraid" },
    { "fr": "être amoureux", "pron": "etr ah-moo-RUH", "en": "to be in love" },
    { "fr": "un ami / une amie", "pron": "uhn-nah-MEE", "en": "a friend" },
    { "fr": "un(e) petit(e) ami(e)", "pron": "puh-tee-tah-MEE", "en": "a boyfriend / girlfriend" },
    { "fr": "sortir avec quelqu'un", "pron": "sor-teer ah-vek kel-KUHN", "en": "to date someone" },
    { "fr": "se marier", "pron": "suh mah-ree-AY", "en": "to get married" },
    { "fr": "rompre", "pron": "ROHNPR", "en": "to break up" },
    { "fr": "Je t'aime.", "pron": "zhuh TEM", "en": "I love you." },
    { "fr": "Tu me manques.", "pron": "tü muh MAHNK", "en": "I miss you." },
    { "fr": "Félicitations !", "pron": "fay-lee-see-tah-SYOHN", "en": "Congratulations!" },
    { "fr": "Ça me fait plaisir.", "pron": "sah muh fay play-ZEER", "en": "That makes me happy." },
    { "fr": "faire la bise", "pron": "fair lah BEEZ", "en": "to greet with cheek kisses" },
    { "fr": "un chum / une blonde", "pron": "uhn TCHOM / ün BLOHND", "en": "boyfriend / girlfriend (🇨🇦)" }
  ],

  "27": [
    { "fr": "un voyage", "pron": "uhn vwah-YAHZH", "en": "a trip" },
    { "fr": "l'aéroport", "pron": "lah-ay-ro-POR", "en": "the airport" },
    { "fr": "un vol", "pron": "uhn VOL", "en": "a flight" },
    { "fr": "un passeport", "pron": "uhn pahs-POR", "en": "a passport" },
    { "fr": "les bagages", "pron": "lay bah-GAHZH", "en": "the luggage" },
    { "fr": "un hôtel", "pron": "uhn oh-TEL", "en": "a hotel" },
    { "fr": "une chambre double", "pron": "ün shahnbr DOOBL", "en": "a double room" },
    { "fr": "une réservation", "pron": "ün ray-zair-vah-SYOHN", "en": "a reservation" },
    { "fr": "la clé de la chambre", "pron": "lah klay duh lah SHAHNBR", "en": "the room key" },
    { "fr": "le TGV", "pron": "luh tay-zhay-VAY", "en": "the high-speed train" },
    { "fr": "un musée", "pron": "uhn mü-ZAY", "en": "a museum" },
    { "fr": "une visite guidée", "pron": "ün vee-zeet gee-DAY", "en": "a guided tour" },
    { "fr": "un jour férié", "pron": "uhn zhoor fay-ree-AY", "en": "a public holiday" },
    { "fr": "la Fête nationale", "pron": "lah fet nah-syo-NAL", "en": "Bastille Day (14 July)" },
    { "fr": "l'office de tourisme", "pron": "lo-fees duh too-REEZM", "en": "the tourist office" },
    { "fr": "Je voudrais réserver.", "pron": "zhuh voo-dray ray-zair-VAY", "en": "I'd like to book." },
    { "fr": "À quelle heure part le train ?", "pron": "ah kel uhr par luh TRAN", "en": "What time does the train leave?" },
    { "fr": "Bon voyage !", "pron": "bohn vwah-YAHZH", "en": "Have a good trip!" }
  ],

  "28": [
    { "fr": "le Québec", "pron": "luh kay-BEK", "en": "Québec (the province)" },
    { "fr": "Montréal", "pron": "mohn-ray-AL", "en": "Montréal" },
    { "fr": "la Ville de Québec", "pron": "lah veel duh kay-BEK", "en": "Québec City" },
    { "fr": "l'Acadie", "pron": "lah-kah-DEE", "en": "Acadia" },
    { "fr": "un(e) Québécois(e)", "pron": "uhn kay-bay-KWAH", "en": "a Quebecer" },
    { "fr": "le Carnaval", "pron": "luh kar-nah-VAL", "en": "the Winter Carnival" },
    { "fr": "la Saint-Jean-Baptiste", "pron": "lah san-zhahn bah-TEEST", "en": "Québec's national holiday (24 June)" },
    { "fr": "une cabane à sucre", "pron": "ün kah-ban ah SÜKR", "en": "a maple sugar shack" },
    { "fr": "le sirop d'érable", "pron": "luh see-roh day-RABL", "en": "maple syrup" },
    { "fr": "la tire sur la neige", "pron": "lah teer sür lah NEZH", "en": "maple taffy on snow" },
    { "fr": "une tourtière", "pron": "ün toor-tee-AIR", "en": "a Québécois meat pie" },
    { "fr": "un dépanneur", "pron": "uhn day-pah-NUHR", "en": "a corner store" },
    { "fr": "la loi 101", "pron": "lah lwah sahn-ün", "en": "Bill 101 (the language law)" },
    { "fr": "Bienvenue !", "pron": "bee-en-vuh-NÜ", "en": "You're welcome! (🇨🇦)" },
    { "fr": "C'est plate.", "pron": "say PLAT", "en": "That's boring. (🇨🇦)" },
    { "fr": "avoir du fun", "pron": "ah-vwahr dü FUN", "en": "to have fun (🇨🇦)" },
    { "fr": "une poutine", "pron": "ün poo-TEEN", "en": "poutine" },
    { "fr": "l'hiver québécois", "pron": "lee-vair kay-bay-KWAH", "en": "the Québec winter" }
  ]
};
