/* vocab-data.js — curated review vocabulary for the French ADVANCED course (C1–C2).

   Consumed by learn.js, the shared glossary.js and the companion pages. Keyed by
   lesson number, plus a "titles" map and a "levels" map (lesson -> CEFR band).
   Each word is { fr, pron, en }. There is deliberately no "slugs" map: the
   advanced pages are numbered, so learn.js and cando.js fall back to
   french_lesson_N.html on their own. There are also deliberately no "img" keys —
   the vocabulary at this tier is grammatical and abstract metalanguage.

   Write accents and emoji as LITERAL characters — build_anki.py parses this file
   as JSON and JS-only \u{...} escapes will break it. */
window.FRENCH_VOCAB = {
  "titles": {
    "1": "Le Subjonctif sans Limites",
    "2": "La Phrase Longue & la Mise en Relief",
    "3": "Le Style Nominal & l’Abstraction",
    "4": "Les Connecteurs Logiques à C1",
    "5": "Les Pronoms à la Limite",
    "6": "Régime Prépositionnel & Collocations",
    "7": "Les Accords Difficiles",
    "8": "Liaison, Enchaînement & Prosodie",
    "9": "La Grammaire du Français Parlé",
    "10": "Atténuation, Implicite & Politesse",
    "11": "La Francophonie Européenne",
    "12": "Francophonie Africaine, Maghrébine & Créole",
    "13": "Humour, Jeux de Mots & Second Degré",
    "14": "L’Histoire des Mots",
    "15": "Orthographe, Ponctuation & Typographie",
    "16": "Le Français Académique",
    "17": "La Langue Juridique & Administrative",
    "18": "Le Français des Affaires",
    "19": "Rhétorique, Discours Public & Langue de Bois",
    "20": "Lire la Littérature : la Prose",
    "21": "La Poésie Française : Versification",
    "22": "Traduire : les Intraduisibles",
    "23": "Langue, Identité & Institutions",
    "24": "DALF C1 & C2 + Plan de Maîtrise"
  },

  "levels": {
    "1": "C1", "2": "C1", "3": "C1", "4": "C1", "5": "C1", "6": "C1", "7": "C1",
    "8": "C1", "9": "C1", "10": "C1", "11": "C1", "12": "C1", "13": "C1",
    "14": "C2", "15": "C2", "16": "C2", "17": "C2", "18": "C2", "19": "C2",
    "20": "C2", "21": "C2", "22": "C2", "23": "C2", "24": "C2"
  },

  "1": [
    { "fr": "quoi que", "pron": "kwah kuh", "en": "whatever (+ subjunctive)" },
    { "fr": "quoique", "pron": "kwah-kuh", "en": "although (+ subjunctive)" },
    { "fr": "quel que soit", "pron": "kel kuh SWAH", "en": "whatever / whichever may be" },
    { "fr": "où que", "pron": "oo kuh", "en": "wherever (+ subjunctive)" },
    { "fr": "si étrange que cela paraisse", "pron": "see ay-TRAHNZH kuh suh-lah pah-RES", "en": "however strange it may seem" },
    { "fr": "pour peu que", "pron": "poor puh kuh", "en": "if only, provided that" },
    { "fr": "ne fût-ce que", "pron": "nuh FÜT-suh kuh", "en": "if only, even just" },
    { "fr": "le fait que", "pron": "luh FAY kuh", "en": "the fact that" },
    { "fr": "à supposer que", "pron": "ah sü-po-ZAY kuh", "en": "supposing that" },
    { "fr": "pour autant que je sache", "pron": "poor oh-TAHN kuh zhuh SAHSH", "en": "as far as I know" },
    { "fr": "je cherche quelqu’un qui sache", "pron": "zhuh shairsh kel-KUHN kee SAHSH", "en": "I am looking for someone who knows" },
    { "fr": "le seul qui puisse", "pron": "luh suhl kee PWEES", "en": "the only one who can" },
    { "fr": "non que", "pron": "nohn kuh", "en": "not that (+ subjunctive)" },
    { "fr": "de sorte que", "pron": "duh SORT kuh", "en": "so that / with the result that" },
    { "fr": "il n’est pas exclu que", "pron": "eel nay pah ex-KLÜ kuh", "en": "it is not out of the question that" },
    { "fr": "que je le veuille ou non", "pron": "kuh zhuh luh VUH-yuh oo nohn", "en": "whether I like it or not" },
    { "fr": "dût-il en souffrir", "pron": "DÜ-teel ahn soo-FREER", "en": "even if he should suffer for it" },
    { "fr": "fût-il président", "pron": "FÜ-teel pray-zee-DAHN", "en": "even if he were president" },
    { "fr": "le subjonctif plus-que-parfait", "pron": "luh süb-zhohnk-TEEF plüs-kuh-par-FAY", "en": "the pluperfect subjunctive" },
    { "fr": "une concession", "pron": "ün kohn-say-SYOHN", "en": "a concession" }
  ],

  "2": [
    { "fr": "la mise en relief", "pron": "lah meez ahn ruh-LYEF", "en": "emphasis, foregrounding" },
    { "fr": "c’est… qui", "pron": "say kee", "en": "it is… who (subject cleft)" },
    { "fr": "c’est… que", "pron": "say kuh", "en": "it is… that (object cleft)" },
    { "fr": "ce que je veux, c’est", "pron": "suh kuh zhuh VUH say", "en": "what I want is" },
    { "fr": "ce dont il s’agit", "pron": "suh dohn eel sah-ZHEE", "en": "what it is about" },
    { "fr": "une proposition subordonnée", "pron": "ün pro-po-zee-syohn sü-bor-do-NAY", "en": "a subordinate clause" },
    { "fr": "une proposition principale", "pron": "ün pro-po-zee-syohn pran-see-PAHL", "en": "a main clause" },
    { "fr": "une incise", "pron": "ün an-SEEZ", "en": "a parenthetical clause" },
    { "fr": "l’antéposition", "pron": "lahn-tay-po-zee-SYOHN", "en": "fronting, placing before" },
    { "fr": "la dislocation", "pron": "lah dees-lo-kah-SYOHN", "en": "dislocation (moi, je…)" },
    { "fr": "à peine était-il arrivé", "pron": "ah PEN ay-tay-teel ah-ree-VAY", "en": "hardly had he arrived" },
    { "fr": "aussi devons-nous", "pron": "oh-SEE duh-vohn NOO", "en": "therefore we must" },
    { "fr": "encore faut-il", "pron": "ahn-KOR foh-TEEL", "en": "even so, one must" },
    { "fr": "peut-être a-t-il raison", "pron": "puh-TETR ah-teel ray-ZOHN", "en": "perhaps he is right" },
    { "fr": "l’inversion du sujet", "pron": "lan-vair-syohn dü sü-ZHAY", "en": "subject inversion" },
    { "fr": "un groupe rythmique", "pron": "uhn groop reet-MEEK", "en": "a rhythm group" },
    { "fr": "la période", "pron": "lah pay-ree-OD", "en": "the periodic sentence" },
    { "fr": "l’emphase", "pron": "lahn-FAHZ", "en": "emphasis" },
    { "fr": "une apposition", "pron": "ün ah-po-zee-SYOHN", "en": "an appositive" },
    { "fr": "un connecteur", "pron": "uhn ko-nek-TUHR", "en": "a connective" }
  ],

  "3": [
    { "fr": "le style nominal", "pron": "luh steel no-mee-NAHL", "en": "nominal style" },
    { "fr": "la nominalisation", "pron": "lah no-mee-nah-lee-zah-SYOHN", "en": "nominalisation" },
    { "fr": "la mise en œuvre", "pron": "lah meez ahn UHVR", "en": "the implementation" },
    { "fr": "la prise en compte", "pron": "lah preez ahn KOHNT", "en": "the taking into account" },
    { "fr": "l’accroissement", "pron": "lah-krwahs-MAHN", "en": "the increase" },
    { "fr": "la baisse", "pron": "lah BES", "en": "the fall, the decrease" },
    { "fr": "le dispositif", "pron": "luh dees-po-zee-TEEF", "en": "the scheme, the arrangement" },
    { "fr": "l’enjeu", "pron": "lahn-ZHUH", "en": "the stake, what is at issue" },
    { "fr": "le constat", "pron": "luh kohn-STAH", "en": "the observation, the finding" },
    { "fr": "la portée", "pron": "lah por-TAY", "en": "the scope, the significance" },
    { "fr": "en quoi", "pron": "ahn KWAH", "en": "in what way, how" },
    { "fr": "ce en quoi", "pron": "suh ahn KWAH", "en": "that in which" },
    { "fr": "l’abstraction", "pron": "lahb-strak-SYOHN", "en": "abstraction" },
    { "fr": "un phénomène", "pron": "uhn fay-no-MEN", "en": "a phenomenon" },
    { "fr": "une tendance lourde", "pron": "ün tahn-dahns LOORD", "en": "a deep-seated trend" },
    { "fr": "l’émergence", "pron": "lay-mair-ZHAHNS", "en": "the emergence" },
    { "fr": "le recours à", "pron": "luh ruh-KOOR ah", "en": "the resort to, the use of" },
    { "fr": "la remise en question", "pron": "lah ruh-meez ahn kes-TYOHN", "en": "the calling into question" },
    { "fr": "un allongement", "pron": "uhn ah-lohnzh-MAHN", "en": "a lengthening" },
    { "fr": "l’aboutissement", "pron": "lah-boo-tees-MAHN", "en": "the culmination, the outcome" }
  ],

  "4": [
    { "fr": "or", "pron": "or", "en": "now, yet (pivot connective)" },
    { "fr": "en revanche", "pron": "ahn ruh-VAHNSH", "en": "on the other hand" },
    { "fr": "certes… mais", "pron": "SAIRT may", "en": "admittedly… but" },
    { "fr": "il n’en demeure pas moins que", "pron": "eel nahn duh-MUHR pah mwan kuh", "en": "the fact remains that" },
    { "fr": "force est de constater que", "pron": "FORS ay duh kohn-stah-TAY kuh", "en": "one is bound to note that" },
    { "fr": "d’autant plus que", "pron": "doh-tahn PLÜ kuh", "en": "all the more so because" },
    { "fr": "d’autant moins que", "pron": "doh-tahn MWAN kuh", "en": "all the less so because" },
    { "fr": "quitte à", "pron": "KEET ah", "en": "even if it means" },
    { "fr": "encore que", "pron": "ahn-KOR kuh", "en": "although, albeit (+ subj.)" },
    { "fr": "à ceci près que", "pron": "ah suh-SEE pray kuh", "en": "except that" },
    { "fr": "en tout état de cause", "pron": "ahn too tay-tah duh KOHZ", "en": "in any event" },
    { "fr": "cela étant", "pron": "suh-lah ay-TAHN", "en": "that being so" },
    { "fr": "toujours est-il que", "pron": "too-zhoor ay-TEEL kuh", "en": "the fact is that" },
    { "fr": "à plus forte raison", "pron": "ah plü fort ray-ZOHN", "en": "all the more reason" },
    { "fr": "loin de là", "pron": "lwan duh LAH", "en": "far from it" },
    { "fr": "autrement dit", "pron": "oh-truh-mahn DEE", "en": "in other words" },
    { "fr": "à savoir", "pron": "ah sah-VWAHR", "en": "namely" },
    { "fr": "sous réserve de", "pron": "soo ray-ZAIRV duh", "en": "subject to" },
    { "fr": "faute de quoi", "pron": "foht duh KWAH", "en": "failing which" },
    { "fr": "en définitive", "pron": "ahn day-fee-nee-TEEV", "en": "ultimately, in the end" }
  ],

  "5": [
    { "fr": "un pronom clitique", "pron": "uhn pro-nohn klee-TEEK", "en": "a clitic pronoun" },
    { "fr": "l’ordre des pronoms", "pron": "lordr day pro-NOHN", "en": "pronoun order" },
    { "fr": "le lui / la leur", "pron": "luh LWEE / lah LUHR", "en": "it to him / it to them" },
    { "fr": "m’en / t’en / s’en", "pron": "MAHN / TAHN / SAHN", "en": "some of it to me / you / oneself" },
    { "fr": "il y en a", "pron": "eel yahn AH", "en": "there are some" },
    { "fr": "le pronom neutre", "pron": "luh pro-nohn NUHTR", "en": "the neuter pronoun le" },
    { "fr": "je le sais", "pron": "zhuh luh SAY", "en": "I know (it / that fact)" },
    { "fr": "celui de mon frère", "pron": "suh-lwee duh mohn FRAIR", "en": "my brother’s (one)" },
    { "fr": "celle qui compte", "pron": "sel kee KOHNT", "en": "the one that matters" },
    { "fr": "ceux d’entre nous", "pron": "suh dahntr NOO", "en": "those of us" },
    { "fr": "soi-même", "pron": "swah-MEM", "en": "oneself" },
    { "fr": "chacun pour soi", "pron": "shah-kuhn poor SWAH", "en": "every man for himself" },
    { "fr": "s’en aller", "pron": "sahn ah-LAY", "en": "to leave, to go away" },
    { "fr": "y penser", "pron": "ee pahn-SAY", "en": "to think about it" },
    { "fr": "s’y faire", "pron": "see FAIR", "en": "to get used to it" },
    { "fr": "s’en vouloir", "pron": "sahn voo-LWAHR", "en": "to be angry with oneself" },
    { "fr": "l’antécédent", "pron": "lahn-tay-say-DAHN", "en": "the antecedent" },
    { "fr": "auprès de qui", "pron": "oh-pray duh KEE", "en": "with whom, from whom" },
    { "fr": "au sujet duquel", "pron": "oh sü-zhay dü-KEL", "en": "about which" },
    { "fr": "le redoublement", "pron": "luh ruh-doo-bluh-MAHN", "en": "doubling, reduplication" }
  ],

  "6": [
    { "fr": "le régime prépositionnel", "pron": "luh ray-zheem pray-po-zee-syo-NEL", "en": "prepositional government" },
    { "fr": "une collocation", "pron": "ün ko-lo-kah-SYOHN", "en": "a collocation" },
    { "fr": "prendre une décision", "pron": "prahndr ün day-see-ZYOHN", "en": "to make a decision" },
    { "fr": "pousser un cri", "pron": "poo-say uhn KREE", "en": "to let out a cry" },
    { "fr": "tirer une conclusion", "pron": "tee-ray ün kohn-klü-ZYOHN", "en": "to draw a conclusion" },
    { "fr": "mener une enquête", "pron": "muh-nay ün ahn-KET", "en": "to conduct an investigation" },
    { "fr": "porter plainte", "pron": "por-tay PLANT", "en": "to file a complaint" },
    { "fr": "combler un retard", "pron": "kohn-blay uhn ruh-TAR", "en": "to make up a delay" },
    { "fr": "être sensible à", "pron": "etr sahn-SEEBL ah", "en": "to be sensitive to" },
    { "fr": "être propice à", "pron": "etr pro-PEES ah", "en": "to be favourable to" },
    { "fr": "être dénué de", "pron": "etr day-nü-AY duh", "en": "to be devoid of" },
    { "fr": "avide de", "pron": "ah-VEED duh", "en": "eager for" },
    { "fr": "conforme à", "pron": "kohn-FORM ah", "en": "in accordance with" },
    { "fr": "au détriment de", "pron": "oh day-tree-mahn duh", "en": "to the detriment of" },
    { "fr": "à l’égard de", "pron": "ah lay-GAR duh", "en": "with regard to" },
    { "fr": "par le biais de", "pron": "par luh BYAY duh", "en": "by means of, through" },
    { "fr": "en dépit de", "pron": "ahn day-PEE duh", "en": "in spite of" },
    { "fr": "un souci de", "pron": "uhn soo-SEE duh", "en": "a concern for" },
    { "fr": "une prise de conscience", "pron": "ün preez duh kohn-SYAHNS", "en": "a realisation, an awareness" },
    { "fr": "un cruel manque de", "pron": "uhn krü-el MAHNK duh", "en": "a sore lack of" }
  ],

  "7": [
    { "fr": "l’accord", "pron": "lah-KOR", "en": "agreement (grammatical)" },
    { "fr": "tout autre", "pron": "too-TOTR", "en": "any other / quite another" },
    { "fr": "toute la journée", "pron": "toot lah zhoor-NAY", "en": "all day long" },
    { "fr": "tout heureux", "pron": "too-tuh-RUH", "en": "quite happy (tout = adverb)" },
    { "fr": "elles sont tout étonnées", "pron": "el sohn too-tay-to-NAY", "en": "they are quite astonished" },
    { "fr": "les mêmes erreurs", "pron": "lay mem zay-RUHR", "en": "the same mistakes" },
    { "fr": "eux-mêmes", "pron": "uh-MEM", "en": "themselves" },
    { "fr": "quelque cent personnes", "pron": "kel-kuh sahn pair-SON", "en": "some hundred people" },
    { "fr": "quelles que soient les raisons", "pron": "kel kuh swah lay ray-ZOHN", "en": "whatever the reasons may be" },
    { "fr": "telle une ombre", "pron": "tel ün OHNBR", "en": "like a shadow" },
    { "fr": "leurs affaires", "pron": "luhr zah-FAIR", "en": "their belongings" },
    { "fr": "une demi-heure", "pron": "ün duh-mee-UHR", "en": "half an hour" },
    { "fr": "nu-pieds", "pron": "nü-PYAY", "en": "barefoot" },
    { "fr": "ci-joint la facture", "pron": "see-zhwan lah fak-TÜR", "en": "please find enclosed the invoice" },
    { "fr": "quatre-vingts ans", "pron": "kah-truh-van ZAHN", "en": "eighty years" },
    { "fr": "deux cents pages", "pron": "duh sahn PAHZH", "en": "two hundred pages" },
    { "fr": "des robes orange", "pron": "day rob o-RAHNZH", "en": "orange dresses (invariable)" },
    { "fr": "des yeux bleu clair", "pron": "day zyuh bluh KLAIR", "en": "light blue eyes (invariable)" },
    { "fr": "je les ai fait venir", "pron": "zhuh lay zay fay vuh-NEER", "en": "I had them come (fait invariable)" },
    { "fr": "plutôt que plus tôt", "pron": "plü-TOH kuh plü TOH", "en": "rather than earlier" }
  ],

  "8": [
    { "fr": "la liaison obligatoire", "pron": "lah lyay-zohn o-blee-gah-TWAHR", "en": "obligatory liaison" },
    { "fr": "la liaison interdite", "pron": "lah lyay-zohn an-tair-DEET", "en": "forbidden liaison" },
    { "fr": "la liaison facultative", "pron": "lah lyay-zohn fah-kül-tah-TEEV", "en": "optional liaison" },
    { "fr": "l’enchaînement", "pron": "lahn-shen-MAHN", "en": "enchaînement, consonant carry-over" },
    { "fr": "le h aspiré", "pron": "luh AHSH ahs-pee-RAY", "en": "the aspirate h" },
    { "fr": "les haricots", "pron": "lay ah-ree-KOH", "en": "the beans (no liaison)" },
    { "fr": "le e caduc", "pron": "luh uh kah-DÜK", "en": "the unstable e, schwa" },
    { "fr": "la loi des trois consonnes", "pron": "lah lwah day trwah kohn-SON", "en": "the three-consonant rule" },
    { "fr": "une syllabe ouverte", "pron": "ün see-lahb oo-VAIRT", "en": "an open syllable" },
    { "fr": "l’accent d’insistance", "pron": "lak-sahn dan-sees-TAHNS", "en": "the emphatic stress" },
    { "fr": "l’intonation montante", "pron": "lan-to-nah-syohn mohn-TAHNT", "en": "rising intonation" },
    { "fr": "un cuir", "pron": "uhn KWEER", "en": "a false liaison in t" },
    { "fr": "un velours", "pron": "uhn vuh-LOOR", "en": "a false liaison in z" },
    { "fr": "le pataquès", "pron": "luh pah-tah-KES", "en": "a botched liaison" },
    { "fr": "la dénasalisation", "pron": "lah day-nah-zah-lee-zah-SYOHN", "en": "denasalisation (bon ami)" },
    { "fr": "l’assimilation", "pron": "lah-see-mee-lah-SYOHN", "en": "assimilation (je pense → chpense)" },
    { "fr": "une voyelle nasale", "pron": "ün vwah-yel nah-ZAHL", "en": "a nasal vowel" },
    { "fr": "un groupe de souffle", "pron": "uhn groop duh SOOFL", "en": "a breath group" },
    { "fr": "la syllabation", "pron": "lah see-lah-bah-SYOHN", "en": "syllabification" },
    { "fr": "il est huit heures", "pron": "eel ay wee-TUHR", "en": "it is eight o’clock" }
  ]
  ,
  "9": [
    { "fr": "y’a pas de souci", "pron": "yah pah duh soo-SEE", "en": "no worries (spoken)" },
    { "fr": "chuis crevé", "pron": "shwee kruh-VAY", "en": "I’m shattered (je suis)" },
    { "fr": "t’as vu ?", "pron": "tah VÜ", "en": "did you see? (tu as)" },
    { "fr": "du coup", "pron": "dü KOO", "en": "so, as a result (filler)" },
    { "fr": "genre", "pron": "ZHAHNR", "en": "like, sort of (filler)" },
    { "fr": "quoi", "pron": "KWAH", "en": "you know (sentence-final tag)" },
    { "fr": "ben", "pron": "BAN", "en": "well… (hesitation)" },
    { "fr": "bon ben voilà", "pron": "bohn ban vwah-LAH", "en": "well, there you go" },
    { "fr": "hein ?", "pron": "AN", "en": "eh? right?" },
    { "fr": "tu vas où ?", "pron": "tü vah OO", "en": "where are you going? (in situ)" },
    { "fr": "il est où, mon sac ?", "pron": "eel ay OO mohn SAK", "en": "where’s my bag? (dislocated)" },
    { "fr": "moi, je trouve que", "pron": "mwah zhuh troov kuh", "en": "personally, I think that" },
    { "fr": "ça me saoule", "pron": "sah muh SOOL", "en": "it does my head in" },
    { "fr": "j’sais pas", "pron": "shay PAH", "en": "dunno (je ne sais pas)" },
    { "fr": "faut qu’on y aille", "pron": "foh kohn-nee AHY", "en": "we’ve got to go" },
    { "fr": "c’est pas grave", "pron": "say pah GRAHV", "en": "it doesn’t matter" },
    { "fr": "enfin bref", "pron": "ahn-fan BREF", "en": "anyway, long story short" },
    { "fr": "en fait", "pron": "ahn FET", "en": "actually, in fact" },
    { "fr": "voilà quoi", "pron": "vwah-lah KWAH", "en": "that’s about it" },
    { "fr": "un tic de langage", "pron": "uhn teek duh lahn-GAHZH", "en": "a verbal tic" }
  ],

  "10": [
    { "fr": "l’atténuation", "pron": "lah-tay-nü-ah-SYOHN", "en": "hedging, softening" },
    { "fr": "la litote", "pron": "lah lee-TOT", "en": "litotes, understatement" },
    { "fr": "ce n’est pas mal", "pron": "suh nay pah MAHL", "en": "it’s rather good (litotes)" },
    { "fr": "il me semble que", "pron": "eel muh SAHNBL kuh", "en": "it seems to me that" },
    { "fr": "je dirais même que", "pron": "zhuh dee-ray MEM kuh", "en": "I would even say that" },
    { "fr": "si je puis dire", "pron": "see zhuh pwee DEER", "en": "if I may say so" },
    { "fr": "je me permets de", "pron": "zhuh muh pair-MAY duh", "en": "I take the liberty of" },
    { "fr": "auriez-vous l’amabilité de", "pron": "oh-ryay voo lah-mah-bee-lee-TAY duh", "en": "would you be so kind as to" },
    { "fr": "je ne voudrais pas abuser", "pron": "zhuh nuh voo-dray pah ah-bü-ZAY", "en": "I don’t want to impose" },
    { "fr": "cela m’ennuierait de", "pron": "suh-lah mahn-nwee-RAY duh", "en": "I would rather not" },
    { "fr": "je crains que ce ne soit difficile", "pron": "zhuh kran kuh suh nuh swah dee-fee-SEEL", "en": "I’m afraid that would be difficult" },
    { "fr": "ce n’est pas faute d’avoir essayé", "pron": "suh nay pah foht dah-vwahr ay-say-YAY", "en": "not for want of trying" },
    { "fr": "sauf erreur de ma part", "pron": "sohf ay-ruhr duh mah PAR", "en": "unless I’m mistaken" },
    { "fr": "avec tout le respect que je vous dois", "pron": "ah-vek too luh res-PAY kuh zhuh voo DWAH", "en": "with all due respect" },
    { "fr": "une réclamation", "pron": "ün ray-klah-mah-SYOHN", "en": "a complaint" },
    { "fr": "un reproche voilé", "pron": "uhn ruh-PROSH vwah-LAY", "en": "a veiled reproach" },
    { "fr": "un sous-entendu", "pron": "uhn soo-zahn-tahn-DÜ", "en": "an implication, an innuendo" },
    { "fr": "l’implicite", "pron": "lan-plee-SEET", "en": "what is implied" },
    { "fr": "le tutoiement de rigueur", "pron": "luh tü-twah-mahn duh ree-GUHR", "en": "expected use of tu" },
    { "fr": "un euphémisme", "pron": "uhn uh-fay-MEESM", "en": "a euphemism" }
  ],

  "11": [
    { "fr": "septante", "pron": "sep-TAHNT", "en": "seventy (🇧🇪 🇨🇭)" },
    { "fr": "octante / huitante", "pron": "ok-TAHNT / wee-TAHNT", "en": "eighty (🇨🇭 Vaud, Valais)" },
    { "fr": "nonante", "pron": "no-NAHNT", "en": "ninety (🇧🇪 🇨🇭)" },
    { "fr": "un belgicisme", "pron": "uhn bel-zhee-SEESM", "en": "a Belgian usage" },
    { "fr": "un helvétisme", "pron": "uhn el-vay-TEESM", "en": "a Swiss usage" },
    { "fr": "une drache", "pron": "ün DRAHSH", "en": "a downpour (🇧🇪)" },
    { "fr": "s’il vous plaît (= voici)", "pron": "seel voo PLAY", "en": "here you are (🇧🇪 usage)" },
    { "fr": "déjeuner (= petit-déjeuner)", "pron": "day-zhuh-NAY", "en": "breakfast (🇧🇪 🇨🇭)" },
    { "fr": "dîner (= déjeuner)", "pron": "dee-NAY", "en": "lunch (🇧🇪 🇨🇭)" },
    { "fr": "souper (= dîner)", "pron": "soo-PAY", "en": "supper, evening meal (🇧🇪 🇨🇭 🇨🇦)" },
    { "fr": "une bourgmestre", "pron": "ün boorg-MESTR", "en": "a mayor (🇧🇪)" },
    { "fr": "le natel", "pron": "luh nah-TEL", "en": "mobile phone (🇨🇭)" },
    { "fr": "une panosse", "pron": "ün pah-NOS", "en": "a floor cloth (🇨🇭)" },
    { "fr": "un cornet", "pron": "uhn kor-NAY", "en": "a carrier bag (🇨🇭)" },
    { "fr": "la Wallonie", "pron": "lah wah-lo-NEE", "en": "Wallonia" },
    { "fr": "la Suisse romande", "pron": "lah swees ro-MAHND", "en": "French-speaking Switzerland" },
    { "fr": "une fédération", "pron": "ün fay-day-rah-SYOHN", "en": "a federation" },
    { "fr": "le plurilinguisme", "pron": "luh plü-ree-lan-GWEESM", "en": "multilingualism" },
    { "fr": "un fonctionnaire européen", "pron": "uhn fohnk-syo-nair uh-ro-pay-AN", "en": "a European civil servant" },
    { "fr": "la norme de référence", "pron": "lah norm duh ray-fay-RAHNS", "en": "the reference standard" }
  ],

  "12": [
    { "fr": "la francophonie", "pron": "lah frahn-ko-fo-NEE", "en": "the French-speaking world" },
    { "fr": "l’OIF", "pron": "lo-ee-EF", "en": "the Organisation internationale de la Francophonie" },
    { "fr": "le nouchi", "pron": "luh noo-SHEE", "en": "Ivorian urban slang" },
    { "fr": "le camfranglais", "pron": "luh kahn-frahn-GLAY", "en": "Cameroonian French-English slang" },
    { "fr": "s’enjailler", "pron": "sahn-zhah-YAY", "en": "to have a great time (🇨🇮)" },
    { "fr": "un go", "pron": "uhn GO", "en": "a girl (nouchi)" },
    { "fr": "être chaud", "pron": "etr SHOH", "en": "to be skilled, on form (Africa)" },
    { "fr": "un taxi-brousse", "pron": "uhn tak-see-BROOS", "en": "a bush taxi" },
    { "fr": "un essencerie", "pron": "ün ay-sahns-REE", "en": "a petrol station (🇸🇳)" },
    { "fr": "la diglossie", "pron": "lah dee-glo-SEE", "en": "diglossia" },
    { "fr": "le créole haïtien", "pron": "luh kray-ol ah-ee-SYAN", "en": "Haitian Creole" },
    { "fr": "un créolisme", "pron": "uhn kray-o-LEESM", "en": "a creole feature" },
    { "fr": "le chiac", "pron": "luh SHYAK", "en": "Acadian French-English mix" },
    { "fr": "l’Acadie", "pron": "lah-kah-DEE", "en": "Acadia" },
    { "fr": "le français cadien", "pron": "luh frahn-say kah-DYAN", "en": "Cajun French" },
    { "fr": "une langue véhiculaire", "pron": "ün lahng vay-ee-kü-LAIR", "en": "a lingua franca" },
    { "fr": "un substrat", "pron": "uhn süb-STRAH", "en": "a substrate (underlying language)" },
    { "fr": "l’insécurité linguistique", "pron": "lan-say-kü-ree-tay lan-gwees-TEEK", "en": "linguistic insecurity" },
    { "fr": "une variété endogène", "pron": "ün vah-ree-ay-tay ahn-do-ZHEN", "en": "a locally developed variety" },
    { "fr": "le brassage", "pron": "luh brah-SAHZH", "en": "mixing, blending" }
  ],

  "13": [
    { "fr": "le second degré", "pron": "luh suh-gohn duh-GRAY", "en": "irony, not-to-be-taken-literally" },
    { "fr": "au premier degré", "pron": "oh pruh-myay duh-GRAY", "en": "literally, at face value" },
    { "fr": "un calembour", "pron": "uhn kah-lahn-BOOR", "en": "a pun" },
    { "fr": "une contrepèterie", "pron": "ün kohn-truh-pet-REE", "en": "a spoonerism" },
    { "fr": "un jeu de mots", "pron": "uhn zhuh duh MOH", "en": "a play on words" },
    { "fr": "l’humour noir", "pron": "lü-moor NWAHR", "en": "black humour" },
    { "fr": "l’autodérision", "pron": "loh-to-day-ree-ZYOHN", "en": "self-deprecation" },
    { "fr": "une vanne", "pron": "ün VAHN", "en": "a quip, a dig" },
    { "fr": "balancer une vanne", "pron": "bah-lahn-say ün VAHN", "en": "to crack a joke at someone" },
    { "fr": "se moquer gentiment", "pron": "suh mo-kay zhahn-tee-MAHN", "en": "to tease good-naturedly" },
    { "fr": "un pince-sans-rire", "pron": "uhn pans-sahn-REER", "en": "a deadpan joker" },
    { "fr": "une pique", "pron": "ün PEEK", "en": "a barbed remark" },
    { "fr": "la satire", "pron": "lah sah-TEER", "en": "satire" },
    { "fr": "un pamphlet", "pron": "uhn pahn-FLAY", "en": "a lampoon, a polemic" },
    { "fr": "une caricature", "pron": "ün kah-ree-kah-TÜR", "en": "a cartoon, a caricature" },
    { "fr": "le trait d’esprit", "pron": "luh tray des-PREE", "en": "the witticism" },
    { "fr": "rire jaune", "pron": "reer ZHOHN", "en": "to give a forced laugh" },
    { "fr": "mourir de rire", "pron": "moo-reer duh REER", "en": "to die laughing" },
    { "fr": "c’est pour rire", "pron": "say poor REER", "en": "it’s only a joke" },
    { "fr": "une niaiserie", "pron": "ün nyay-zuh-REE", "en": "a silly thing (🇨🇦)" }
  ],

  "14": [
    { "fr": "l’étymologie", "pron": "lay-tee-mo-lo-ZHEE", "en": "etymology" },
    { "fr": "un doublet", "pron": "uhn doo-BLAY", "en": "a doublet (two words, one root)" },
    { "fr": "un mot savant", "pron": "uhn moh sah-VAHN", "en": "a learned word" },
    { "fr": "un mot populaire", "pron": "uhn moh po-pü-LAIR", "en": "a word of popular descent" },
    { "fr": "fragile / frêle", "pron": "frah-ZHEEL / FREL", "en": "fragile / frail (a doublet)" },
    { "fr": "hôpital / hôtel", "pron": "oh-pee-TAHL / oh-TEL", "en": "hospital / hotel (a doublet)" },
    { "fr": "le latin vulgaire", "pron": "luh lah-tan vül-GAIR", "en": "Vulgar Latin" },
    { "fr": "le francique", "pron": "luh frahn-SEEK", "en": "Frankish (Germanic superstrate)" },
    { "fr": "le gaulois", "pron": "luh goh-LWAH", "en": "Gaulish" },
    { "fr": "un emprunt", "pron": "uhn ahn-PRUHN", "en": "a loanword" },
    { "fr": "un calque", "pron": "uhn KAHLK", "en": "a calque, a loan translation" },
    { "fr": "un arabisme", "pron": "uhn ah-rah-BEESM", "en": "a word of Arabic origin" },
    { "fr": "un anglicisme", "pron": "uhn ahn-glee-SEESM", "en": "an anglicism" },
    { "fr": "un italianisme", "pron": "uhn ee-tah-lyah-NEESM", "en": "a word of Italian origin" },
    { "fr": "une racine grecque", "pron": "ün rah-seen GREK", "en": "a Greek root" },
    { "fr": "un radical", "pron": "uhn rah-dee-KAHL", "en": "a stem, a root" },
    { "fr": "l’évolution phonétique", "pron": "lay-vo-lü-syohn fo-nay-TEEK", "en": "sound change" },
    { "fr": "l’aphérèse", "pron": "lah-fay-REZ", "en": "aphaeresis (loss of a first syllable)" },
    { "fr": "l’apocope", "pron": "lah-po-KOP", "en": "apocope (clipping the end)" },
    { "fr": "un faux ami savant", "pron": "uhn foh-zah-mee sah-VAHN", "en": "a learned false friend" }
  ]
  ,
  "15": [
    { "fr": "l’orthographe", "pron": "lor-to-GRAHF", "en": "spelling" },
    { "fr": "la rectification de 1990", "pron": "lah rek-tee-fee-kah-syohn duh meel-nuhf-sahn-kah-TRUH-van-dees", "en": "the 1990 spelling reform" },
    { "fr": "un accent circonflexe", "pron": "uhn ak-sahn seer-kohn-FLEX", "en": "a circumflex accent" },
    { "fr": "un tréma", "pron": "uhn tray-MAH", "en": "a diaeresis" },
    { "fr": "une cédille", "pron": "ün say-DEEY", "en": "a cedilla" },
    { "fr": "un trait d’union", "pron": "uhn tray dü-NYOHN", "en": "a hyphen" },
    { "fr": "une espace insécable", "pron": "ün es-pahs an-say-KAHBL", "en": "a non-breaking space" },
    { "fr": "des guillemets français", "pron": "day gee-yuh-may frahn-SAY", "en": "French quotation marks « »" },
    { "fr": "un point-virgule", "pron": "uhn pwan-veer-GÜL", "en": "a semicolon" },
    { "fr": "deux points", "pron": "duh PWAN", "en": "a colon" },
    { "fr": "un tiret cadratin", "pron": "uhn tee-ray kah-drah-TAN", "en": "an em dash" },
    { "fr": "des points de suspension", "pron": "day pwan duh sü-spahn-SYOHN", "en": "an ellipsis" },
    { "fr": "une majuscule", "pron": "ün mah-zhüs-KÜL", "en": "a capital letter" },
    { "fr": "en italique", "pron": "ahn ee-tah-LEEK", "en": "in italics" },
    { "fr": "la ponctuation", "pron": "lah pohnk-tü-ah-SYOHN", "en": "punctuation" },
    { "fr": "une coquille", "pron": "ün ko-KEEY", "en": "a typo" },
    { "fr": "relire une épreuve", "pron": "ruh-leer ün ay-PRUHV", "en": "to proofread a proof" },
    { "fr": "la dictée", "pron": "lah deek-TAY", "en": "the dictation" },
    { "fr": "un barbarisme", "pron": "uhn bar-bah-REESM", "en": "a barbarism, a malformed word" },
    { "fr": "un pléonasme", "pron": "uhn play-o-NAHSM", "en": "a redundancy" }
  ],

  "16": [
    { "fr": "une dissertation", "pron": "ün dee-sair-tah-SYOHN", "en": "an academic essay (French format)" },
    { "fr": "la problématique", "pron": "lah pro-blay-mah-TEEK", "en": "the central research question" },
    { "fr": "un plan dialectique", "pron": "uhn plahn dyah-lek-TEEK", "en": "a thesis-antithesis-synthesis plan" },
    { "fr": "un plan thématique", "pron": "uhn plahn tay-mah-TEEK", "en": "a thematic plan" },
    { "fr": "l’accroche", "pron": "lah-KROSH", "en": "the opening hook" },
    { "fr": "l’annonce du plan", "pron": "lah-nohns dü PLAHN", "en": "the statement of the essay plan" },
    { "fr": "une partie", "pron": "ün par-TEE", "en": "a main section" },
    { "fr": "une transition", "pron": "ün trahn-zee-SYOHN", "en": "a transition" },
    { "fr": "le commentaire composé", "pron": "luh ko-mahn-tair kohn-po-ZAY", "en": "the structured literary commentary" },
    { "fr": "l’explication de texte", "pron": "lex-plee-kah-syohn duh TEXT", "en": "close textual analysis" },
    { "fr": "un axe de lecture", "pron": "uhn ax duh lek-TÜR", "en": "an interpretive angle" },
    { "fr": "étayer un argument", "pron": "ay-tay-yay uhn ar-gü-MAHN", "en": "to support an argument" },
    { "fr": "nuancer un propos", "pron": "nü-ahn-say uhn pro-POH", "en": "to qualify a statement" },
    { "fr": "il convient de souligner", "pron": "eel kohn-vyan duh soo-lee-NYAY", "en": "it should be stressed" },
    { "fr": "on peut dès lors avancer que", "pron": "ohn puh day lor ah-vahn-say kuh", "en": "one may therefore suggest that" },
    { "fr": "citer un auteur", "pron": "see-tay uhn oh-TUHR", "en": "to quote an author" },
    { "fr": "une note de bas de page", "pron": "ün not duh bah duh PAHZH", "en": "a footnote" },
    { "fr": "la bibliographie", "pron": "lah bee-blee-o-grah-FEE", "en": "the bibliography" },
    { "fr": "un corpus", "pron": "uhn kor-PÜS", "en": "a corpus, a body of texts" },
    { "fr": "une copie", "pron": "ün ko-PEE", "en": "an exam script" }
  ],

  "17": [
    { "fr": "un bail", "pron": "uhn BAHY", "en": "a lease" },
    { "fr": "le bailleur", "pron": "luh bah-YUHR", "en": "the lessor, the landlord" },
    { "fr": "le preneur", "pron": "luh pruh-NUHR", "en": "the lessee, the tenant" },
    { "fr": "par la présente", "pron": "par lah pray-ZAHNT", "en": "hereby, by this letter" },
    { "fr": "aux fins de", "pron": "oh fan duh", "en": "for the purposes of" },
    { "fr": "nonobstant", "pron": "no-nob-STAHN", "en": "notwithstanding" },
    { "fr": "ledit contrat", "pron": "luh-dee kohn-TRAH", "en": "the said contract" },
    { "fr": "il est stipulé que", "pron": "eel ay stee-pü-LAY kuh", "en": "it is stipulated that" },
    { "fr": "sous peine de", "pron": "soo PEN duh", "en": "on pain of, failing which" },
    { "fr": "une clause résolutoire", "pron": "ün klohz ray-zo-lü-TWAHR", "en": "a termination clause" },
    { "fr": "un préavis", "pron": "uhn pray-ah-VEE", "en": "a notice period" },
    { "fr": "une mise en demeure", "pron": "ün meez ahn duh-MUHR", "en": "a formal demand letter" },
    { "fr": "un recours gracieux", "pron": "uhn ruh-koor grah-SYUH", "en": "an informal administrative appeal" },
    { "fr": "le Journal officiel", "pron": "luh zhoor-nahl o-fee-SYEL", "en": "the official gazette" },
    { "fr": "un décret", "pron": "uhn day-KRAY", "en": "a decree" },
    { "fr": "un arrêté", "pron": "uhn ah-ray-TAY", "en": "an order, a ruling" },
    { "fr": "une attestation", "pron": "ün ah-tes-tah-SYOHN", "en": "a certificate, a written statement" },
    { "fr": "un justificatif de domicile", "pron": "uhn zhüs-tee-fee-kah-teef duh do-mee-SEEL", "en": "proof of address" },
    { "fr": "la paperasse", "pron": "lah pah-puh-RAHS", "en": "red tape, paperwork" },
    { "fr": "veuillez agréer mes salutations distinguées", "pron": "vuh-yay ah-gray-ay may sah-lü-tah-syohn dees-tan-GAY", "en": "yours faithfully (formal close)" }
  ],

  "18": [
    { "fr": "un compte rendu", "pron": "uhn kohnt rahn-DÜ", "en": "a minute, a written summary" },
    { "fr": "un ordre du jour", "pron": "uhn ordr dü ZHOOR", "en": "an agenda" },
    { "fr": "un relevé de décisions", "pron": "uhn ruh-luh-vay duh day-see-ZYOHN", "en": "a record of decisions" },
    { "fr": "animer une réunion", "pron": "ah-nee-may ün ray-ü-NYOHN", "en": "to chair a meeting" },
    { "fr": "faire un point", "pron": "fair uhn PWAN", "en": "to have a catch-up, to review" },
    { "fr": "un livrable", "pron": "uhn lee-VRAHBL", "en": "a deliverable" },
    { "fr": "une échéance", "pron": "ün ay-shay-AHNS", "en": "a deadline" },
    { "fr": "un cahier des charges", "pron": "uhn kah-yay day SHARZH", "en": "a specification document" },
    { "fr": "un devis", "pron": "uhn duh-VEE", "en": "a quote, an estimate" },
    { "fr": "une marge de négociation", "pron": "ün marzh duh nay-go-syah-SYOHN", "en": "room for negotiation" },
    { "fr": "parvenir à un accord", "pron": "par-vuh-neer ah uhn ah-KOR", "en": "to reach an agreement" },
    { "fr": "revoir sa position", "pron": "ruh-vwahr sah po-zee-SYOHN", "en": "to reconsider one’s position" },
    { "fr": "une contrepartie", "pron": "ün kohn-truh-par-TEE", "en": "a quid pro quo" },
    { "fr": "un enjeu stratégique", "pron": "uhn ahn-zhuh strah-tay-ZHEEK", "en": "a strategic stake" },
    { "fr": "à la hauteur des attentes", "pron": "ah lah oh-tuhr day zah-TAHNT", "en": "up to expectations" },
    { "fr": "le siège social", "pron": "luh syezh so-SYAHL", "en": "the head office" },
    { "fr": "un cadre", "pron": "uhn KAHDR", "en": "a manager, an executive" },
    { "fr": "le service RH", "pron": "luh sair-vees air-AHSH", "en": "the HR department" },
    { "fr": "un PV de réunion", "pron": "uhn pay-VAY duh ray-ü-NYOHN", "en": "formal meeting minutes" },
    { "fr": "dans les meilleurs délais", "pron": "dahn lay may-yuhr day-LAY", "en": "as soon as possible (formal)" }
  ],

  "19": [
    { "fr": "la rhétorique", "pron": "lah ray-to-REEK", "en": "rhetoric" },
    { "fr": "une figure de style", "pron": "ün fee-gür duh STEEL", "en": "a figure of speech" },
    { "fr": "une anaphore", "pron": "ün ah-nah-FOR", "en": "anaphora (repeated opening)" },
    { "fr": "un chiasme", "pron": "uhn KYAHSM", "en": "a chiasmus" },
    { "fr": "une prétérition", "pron": "ün pray-tay-ree-SYOHN", "en": "praeteritio (I shall not mention…)" },
    { "fr": "une hypotypose", "pron": "ün ee-po-tee-POHZ", "en": "vivid description" },
    { "fr": "une gradation", "pron": "ün grah-dah-SYOHN", "en": "a climax, a build-up" },
    { "fr": "une question rhétorique", "pron": "ün kes-tyohn ray-to-REEK", "en": "a rhetorical question" },
    { "fr": "une apostrophe", "pron": "ün ah-pos-TROF", "en": "a direct address" },
    { "fr": "la langue de bois", "pron": "lah lahng duh BWAH", "en": "empty official jargon, doublespeak" },
    { "fr": "un élément de langage", "pron": "uhn ay-lay-mahn duh lahn-GAHZH", "en": "an official talking point" },
    { "fr": "noyer le poisson", "pron": "nwah-yay luh pwah-SOHN", "en": "to dodge the issue" },
    { "fr": "botter en touche", "pron": "bo-tay ahn TOOSH", "en": "to kick into touch, to evade" },
    { "fr": "un plan de charge social", "pron": "uhn plahn duh sharzh so-SYAHL", "en": "a redundancy plan (euphemism)" },
    { "fr": "l’éloquence", "pron": "lay-lo-KAHNS", "en": "eloquence" },
    { "fr": "un orateur", "pron": "uhn o-rah-TUHR", "en": "a speaker, an orator" },
    { "fr": "une allocution", "pron": "ün ah-lo-kü-SYOHN", "en": "a short formal address" },
    { "fr": "un discours d’ouverture", "pron": "uhn dees-koor doo-vair-TÜR", "en": "an opening speech" },
    { "fr": "un parti pris", "pron": "uhn par-tee PREE", "en": "a bias" },
    { "fr": "une prise de parole", "pron": "ün preez duh pah-ROL", "en": "a turn at speaking" }
  ]
  ,
  "20": [
    { "fr": "la focalisation", "pron": "lah fo-kah-lee-zah-SYOHN", "en": "focalisation, point of view" },
    { "fr": "un narrateur omniscient", "pron": "uhn nah-rah-tuhr om-nee-SYAHN", "en": "an omniscient narrator" },
    { "fr": "le style indirect libre", "pron": "luh steel an-dee-rekt LEEBR", "en": "free indirect speech" },
    { "fr": "un incipit", "pron": "uhn an-see-PEET", "en": "an opening (of a novel)" },
    { "fr": "un dénouement", "pron": "uhn day-noo-MAHN", "en": "a resolution, an ending" },
    { "fr": "une intrigue", "pron": "ün an-TREEG", "en": "a plot" },
    { "fr": "un registre tragique", "pron": "uhn ruh-zheestr trah-ZHEEK", "en": "a tragic register" },
    { "fr": "le champ lexical", "pron": "luh shahn lex-ee-KAHL", "en": "the lexical field" },
    { "fr": "une isotopie", "pron": "ün ee-zo-to-PEE", "en": "a recurring semantic thread" },
    { "fr": "une métaphore filée", "pron": "ün may-tah-for fee-LAY", "en": "an extended metaphor" },
    { "fr": "l’ellipse narrative", "pron": "lay-leeps nah-rah-TEEV", "en": "a narrative gap, a time jump" },
    { "fr": "un récit enchâssé", "pron": "uhn ray-see ahn-shah-SAY", "en": "an embedded narrative" },
    { "fr": "une mise en abyme", "pron": "ün meez ahn ah-BEEM", "en": "a story within the story" },
    { "fr": "un archaïsme", "pron": "uhn ar-kah-EESM", "en": "an archaism" },
    { "fr": "un tour vieilli", "pron": "uhn toor vyay-YEE", "en": "a dated turn of phrase" },
    { "fr": "le nouveau roman", "pron": "luh noo-voh ro-MAHN", "en": "the nouveau roman movement" },
    { "fr": "l’autofiction", "pron": "loh-to-feek-SYOHN", "en": "autofiction" },
    { "fr": "une nouvelle", "pron": "ün noo-VEL", "en": "a short story" },
    { "fr": "un procédé d’écriture", "pron": "uhn pro-say-day day-kree-TÜR", "en": "a writing device" },
    { "fr": "une visée critique", "pron": "ün vee-zay kree-TEEK", "en": "a critical intent" }
  ],

  "21": [
    { "fr": "la versification", "pron": "lah vair-see-fee-kah-SYOHN", "en": "versification" },
    { "fr": "un alexandrin", "pron": "uhn ah-lex-ahn-DRAN", "en": "an alexandrine (12 syllables)" },
    { "fr": "un décasyllabe", "pron": "uhn day-kah-see-LAHB", "en": "a decasyllable" },
    { "fr": "un octosyllabe", "pron": "uhn ok-to-see-LAHB", "en": "an octosyllable" },
    { "fr": "un hémistiche", "pron": "uhn ay-mees-TEESH", "en": "a half-line" },
    { "fr": "la césure", "pron": "lah say-ZÜR", "en": "the caesura" },
    { "fr": "un enjambement", "pron": "uhn ahn-zhahnb-MAHN", "en": "an enjambment" },
    { "fr": "un rejet", "pron": "uhn ruh-ZHAY", "en": "a run-over word" },
    { "fr": "une diérèse", "pron": "ün dyay-REZ", "en": "diaeresis (two syllables from one)" },
    { "fr": "une synérèse", "pron": "ün see-nay-REZ", "en": "synaeresis (one syllable from two)" },
    { "fr": "une rime riche", "pron": "ün reem REESH", "en": "a rich rhyme" },
    { "fr": "une rime suffisante", "pron": "ün reem sü-fee-ZAHNT", "en": "a sufficient rhyme" },
    { "fr": "une rime pauvre", "pron": "ün reem POHVR", "en": "a poor rhyme" },
    { "fr": "des rimes plates", "pron": "day reem PLAHT", "en": "couplet rhymes (AABB)" },
    { "fr": "des rimes croisées", "pron": "day reem krwah-ZAY", "en": "alternating rhymes (ABAB)" },
    { "fr": "des rimes embrassées", "pron": "day reem ahn-brah-SAY", "en": "enclosed rhymes (ABBA)" },
    { "fr": "un quatrain", "pron": "uhn kah-TRAN", "en": "a quatrain" },
    { "fr": "un tercet", "pron": "uhn tair-SAY", "en": "a tercet" },
    { "fr": "un sonnet", "pron": "uhn so-NAY", "en": "a sonnet" },
    { "fr": "le vers libre", "pron": "luh vair LEEBR", "en": "free verse" }
  ],

  "22": [
    { "fr": "la traduction", "pron": "lah trah-dük-SYOHN", "en": "translation" },
    { "fr": "le texte source", "pron": "luh text SOORS", "en": "the source text" },
    { "fr": "la langue cible", "pron": "lah lahng SEEBL", "en": "the target language" },
    { "fr": "un intraduisible", "pron": "uhn an-trah-dwee-ZEEBL", "en": "an untranslatable" },
    { "fr": "le dépaysement", "pron": "luh day-pay-eez-MAHN", "en": "the pleasant disorientation of being elsewhere" },
    { "fr": "le terroir", "pron": "luh tair-WAHR", "en": "the land and its character (of produce)" },
    { "fr": "râler", "pron": "rah-LAY", "en": "to grumble (as a national sport)" },
    { "fr": "la débrouillardise", "pron": "lah day-broo-yar-DEEZ", "en": "resourcefulness" },
    { "fr": "un faux ami", "pron": "uhn foh-zah-MEE", "en": "a false friend" },
    { "fr": "actuellement", "pron": "ak-tü-el-MAHN", "en": "currently (NOT actually)" },
    { "fr": "éventuellement", "pron": "ay-vahn-tü-el-MAHN", "en": "possibly (NOT eventually)" },
    { "fr": "assister à", "pron": "ah-sees-TAY ah", "en": "to attend (NOT to assist)" },
    { "fr": "une transposition", "pron": "ün trahns-po-zee-SYOHN", "en": "transposition (change of word class)" },
    { "fr": "une modulation", "pron": "ün mo-dü-lah-SYOHN", "en": "modulation (change of viewpoint)" },
    { "fr": "un étoffement", "pron": "uhn ay-tof-MAHN", "en": "amplification (adding words)" },
    { "fr": "un allègement", "pron": "uhn ah-lezh-MAHN", "en": "economy (cutting words)" },
    { "fr": "une équivalence", "pron": "ün ay-kee-vah-LAHNS", "en": "equivalence (idiom for idiom)" },
    { "fr": "le sous-titrage", "pron": "luh soo-tee-TRAHZH", "en": "subtitling" },
    { "fr": "la fidélité au texte", "pron": "lah fee-day-lee-tay oh TEXT", "en": "fidelity to the text" },
    { "fr": "un traducteur assermenté", "pron": "uhn trah-dük-tuhr ah-sair-mahn-TAY", "en": "a sworn translator" }
  ],

  "23": [
    { "fr": "l’Académie française", "pron": "lah-kah-day-mee frahn-SEZ", "en": "the Académie française" },
    { "fr": "un immortel", "pron": "uhn ee-mor-TEL", "en": "an Academy member" },
    { "fr": "la loi Toubon", "pron": "lah lwah too-BOHN", "en": "the Toubon law (1994)" },
    { "fr": "le purisme", "pron": "luh pü-REESM", "en": "purism" },
    { "fr": "le franglais", "pron": "luh frahn-GLAY", "en": "franglais" },
    { "fr": "l’écriture inclusive", "pron": "lay-kree-tür an-klü-ZEEV", "en": "inclusive writing" },
    { "fr": "le point médian", "pron": "luh pwan may-DYAHN", "en": "the interpunct (étudiant·e·s)" },
    { "fr": "la féminisation des noms de métiers", "pron": "lah fay-mee-nee-zah-syohn day nohn duh may-TYAY", "en": "feminising job titles" },
    { "fr": "une autrice", "pron": "ün oh-TREES", "en": "a female author" },
    { "fr": "une professeure", "pron": "ün pro-fay-SUHR", "en": "a female teacher" },
    { "fr": "l’OQLF", "pron": "lo-kü-el-EF", "en": "Québec’s language office" },
    { "fr": "la Charte de la langue française", "pron": "lah shart duh lah lahng frahn-SEZ", "en": "the Charter of the French Language" },
    { "fr": "un organisme de normalisation", "pron": "uhn or-gah-neesm duh nor-mah-lee-zah-SYOHN", "en": "a standards body" },
    { "fr": "une recommandation officielle", "pron": "ün ruh-ko-mahn-dah-syohn o-fee-SYEL", "en": "an official recommendation" },
    { "fr": "un courriel", "pron": "uhn koo-RYEL", "en": "an email (recommended term)" },
    { "fr": "le rayonnement culturel", "pron": "luh ray-on-mahn kül-tü-REL", "en": "cultural influence" },
    { "fr": "une politique linguistique", "pron": "ün po-lee-teek lan-gwees-TEEK", "en": "a language policy" },
    { "fr": "la norme prescriptive", "pron": "lah norm pres-kreep-TEEV", "en": "the prescriptive standard" },
    { "fr": "l’usage", "pron": "lü-ZAHZH", "en": "usage (what speakers actually do)" },
    { "fr": "le droit à la langue", "pron": "luh drwah ah lah LAHNG", "en": "language rights" }
  ],

  "24": [
    { "fr": "le DALF", "pron": "luh DAHLF", "en": "the DALF diploma (C1/C2)" },
    { "fr": "une synthèse de documents", "pron": "ün san-tez duh do-kü-MAHN", "en": "a synthesis of several documents" },
    { "fr": "un essai argumenté", "pron": "uhn ay-say ar-gü-mahn-TAY", "en": "an argued essay" },
    { "fr": "un exposé", "pron": "uhn ex-po-ZAY", "en": "a presentation" },
    { "fr": "un monologue suivi", "pron": "uhn mo-no-log swee-VEE", "en": "a sustained monologue" },
    { "fr": "un entretien avec l’examinateur", "pron": "uhn ahn-truh-tyan ah-vek leg-zah-mee-nah-TUHR", "en": "a discussion with the examiner" },
    { "fr": "la reformulation", "pron": "lah ruh-for-mü-lah-SYOHN", "en": "rephrasing in your own words" },
    { "fr": "le plagiat de formulation", "pron": "luh plah-zhyah duh for-mü-lah-SYOHN", "en": "copying the source wording" },
    { "fr": "le nombre de mots imposé", "pron": "luh nohnbr duh moh an-po-ZAY", "en": "the required word count" },
    { "fr": "le barème", "pron": "luh bah-REM", "en": "the marking scheme" },
    { "fr": "une note éliminatoire", "pron": "ün not ay-lee-mee-nah-TWAHR", "en": "a disqualifying mark" },
    { "fr": "le domaine lettres et sciences humaines", "pron": "luh do-men letr ay syahns ü-MEN", "en": "the humanities option" },
    { "fr": "le domaine sciences", "pron": "luh do-men SYAHNS", "en": "the science option" },
    { "fr": "gérer son temps", "pron": "zhay-ray sohn TAHN", "en": "to manage one’s time" },
    { "fr": "un plan détaillé", "pron": "uhn plahn day-tah-YAY", "en": "a detailed outline" },
    { "fr": "prendre des notes en écoutant", "pron": "prahndr day not ahn ay-koo-TAHN", "en": "to take notes while listening" },
    { "fr": "un entraînement régulier", "pron": "uhn ahn-tren-mahn ray-gü-LYAY", "en": "regular practice" },
    { "fr": "l’entretien de la langue", "pron": "lahn-truh-tyan duh lah LAHNG", "en": "keeping the language up" },
    { "fr": "un bain linguistique", "pron": "uhn ban lan-gwees-TEEK", "en": "language immersion" },
    { "fr": "la maîtrise", "pron": "lah may-TREEZ", "en": "mastery" }
  ]
};
